#!/bin/bash

# Kalantar ROUND 14 -- OG-T DRAINED START.
#
#   cd /home/saeedvdi/links/projects/def-biaoli66/saeedvdi/projects/orca_4.0/Examples/Kalantar2025
#   sbatch submit_110_round14_ogt_hpc.sh
#
# Submitted separately from the joint-law arms: these are 600 s probes and a 6 h
# reservation starts far sooner than the 48 h one.
#
# WHY.  Rounds 12 and 13 closed off every way of draining this specimen DURING the
# preload, and they did it cleanly:
#
#   110_08  53 s ramp, single-node ports                        dp = 23.70 MPa
#   110_36  ramp 53 s -> 9998 s (189x longer)                   dp = 20.96
#   110_46  line-source ports, 11 nodes spanning the full W     dp = 23.88
#   110_47  line ports + pore pressure 3 MPa on both platens    dp = 23.77
#
# The round-13 ports DID engage -- inj_reaction_sum went -3.74e-9 -> -1.47e-8, a 3.9x
# flux increase -- so that is a falsification, not a null implementation.  Holding
# pressure on the platens did nothing either, because diffusion from mid-height to a
# platen is L^2/c = 1667 s against a 53 s ramp.  AT k = 1.4e-20 m^2 NO DRAINAGE
# BOUNDARY ANYWHERE CAN DRAIN THIS SPECIMEN ON THE TIMESCALE OF THE LOADING.  Ramp
# length is no lever either: dp <= 3 MPa needs T >= 4.7e4 s on the quasi-steady
# estimate, and the measured relief is weaker still (a 189x longer ramp bought 18 %
# in dp/dsigma_d, 0.305 -> 0.249).
#
# THE FIX IS TO STOP SIMULATING THE PRELOAD TRANSIENT.  These decks start from the
# drained, preloaded equilibrium: pore pressure initialised at the production value
# instead of 5 MPa, the axial stress placed in initial_stress, and the axial command
# held at its final value from t = 0.  No ramp.  This is FAITHFUL, not a shortcut --
# Kalantar's specimen reached its preload without failing, so its preload must itself
# have been drained, i.e. slow.
#
# Array map:
#   0  110_55_og_t_drained_start_r14           sigma_1 = 193.43 MPa (the deck's gated value)
#   1  110_56_og_t_drained_start_t2stress_r14  sigma_1 = 185.49 MPa (what Table 2 implies)
#
# WHY THE PAIR.  Table 2 stage 1 gives OG-T tau = 63.21 and sigma'_n = 59.33, so
# sigma_d = tau/(sin.cos) = 63.21/0.4145 = 152.49 MPa at 28 deg and sigma_1 = 185.49 --
# 7.94 MPa below the deck's gated 193.43.  That is +3.29 MPa of tau and +1.75 of
# sigma'_n, which matters because Table 2's own stage 1 already sits at
# tau/sigma'_n = 1.0654: it needs a 46.81 deg friction angle to stand up at all.
# In 110_56 initial_stress and axial_pres_final are BOTH moved, since the command and
# the initial stress must agree or step 1 is not an equilibrium and the probe measures
# the transient it was built to avoid.
#
#   python3 scripts/score_110_round11.py \
#     Examples/Kalantar2025/OGT/results_csv_hpc/110_55_og_t_drained_start_r14_hpc.csv
#
#   1. dp_MPa SHOULD BE NEAR ZERO BY CONSTRUCTION.  This is the deck's self-test, not
#      a physics result: the specimen starts in pore-pressure equilibrium and nothing
#      loads it afterwards.  If dp is not ~0, the initial state is not an equilibrium
#      -- most likely initial_stress and axial_pres_final disagree -- and the run is
#      invalid.  Fix the deck, do not interpret the mechanics.
#   2. tau/tau_limit at sigma_d = 160.43 MPa   < 1.0
#   3. cumulative_plastic_slip at 600 s        < 10 um
#
# GATES 2 AND 3 OF THE SCORER'S PRINTED SET ARE MIS-SPECIFIED; ignore its ratio and
# slope columns.  effective_normal_paper_frame_mpa_pp is a TOTAL stress -- it
# regresses on sigma_d at +0.2544 with no pore-pressure subtraction -- while
# bb_effective_normal_stress_pp is an effective one.  Over 243 pre-slip steps of
# 110_36, bb_eff - (paper_frame - interface_pressure) = +3.151 +- 0.077 MPa, constant
# while sigma_d went 0 -> 82 and p went 0 -> 23.  That constant is p_out.  So the
# ratio is effective/total and cannot reach 0.93 while p is large, by construction.
# With p ~ 0 here the two definitions nearly coincide, so the ratio SHOULD look fine
# in this round -- that is an artefact of the drained start, not evidence about the
# load path.  Do not report it as a pass.
#
# WHAT A DOUBLE FAILURE MEANS.  If BOTH arms still yield, the model is not at fault:
# with p ~ 3 MPa everywhere and the load applied statically there is nothing left of
# the protocol artefact, and the remaining explanation is that Kalantar's reduced
# stresses do not stand up.  That would land beside two doubts the reading notes
# already raise independently -- the 26 deg fracture angle the geometry cannot
# realise, and phi_r = 43.1 deg, which no granite has.  Report it as a finding about
# the data, and DO NOT open a round 15 of constitutive arms on OG-T.
#
# Decks generated by scripts/build_110_kalantar_round14_decks.py; both Syntax OK.

#SBATCH --job-name=kalantar_110_r14_ogt
#SBATCH --chdir=/home/saeedvdi/links/projects/def-biaoli66/saeedvdi/projects/orca_4.0/Examples/Kalantar2025
#SBATCH --account=def-biaoli66
#SBATCH --time=6:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --mem=32G
#SBATCH --array=0-1
#SBATCH --output=kalantar_110_r14_ogt_%A_%a.out
#SBATCH --error=kalantar_110_r14_ogt_%A_%a.err

set -euo pipefail

project_root=/home/saeedvdi/links/projects/def-biaoli66/saeedvdi/projects/orca_4.0
study_root=${project_root}/Examples/Kalantar2025

case "${SLURM_ARRAY_TASK_ID}" in
  0) case_dir=OGT; stem=110_55_og_t_drained_start_r14 ;;
  1) case_dir=OGT; stem=110_56_og_t_drained_start_t2stress_r14 ;;
  *) echo "Unexpected SLURM_ARRAY_TASK_ID=${SLURM_ARRAY_TASK_ID}" >&2; exit 2 ;;
esac

ranks=32
case_path=${study_root}/${case_dir}
input_path=${case_path}/${stem}.i
executable=${project_root}/orca-opt

[[ -f "${input_path}" ]] || { echo "Missing input deck: ${input_path}" >&2; exit 3; }
[[ -x "${executable}" ]] || { echo "Missing application: ${executable}" >&2; exit 4; }

cd "${case_path}"
unset SLURM_MEM_PER_NODE SLURM_MEM_PER_CPU SLURM_MEM_PER_GPU
mkdir -p results_csv_hpc results_exodus_hpc results_checkpoint_hpc logs

echo "Starting array task ${SLURM_ARRAY_TASK_ID}: ${case_dir}/${stem}.i"
echo "SLURM job ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}; ${ranks} ranks, 32G"

srun --mpi=pmi2 -n "${ranks}" "${executable}" -i "${stem}.i" \
  Outputs/chk/enable=false \
  csv_file_base="results_csv_hpc/${stem}_hpc" \
  exodus_file_base="results_exodus_hpc/${stem}_hpc" \
  checkpoint_file_base="results_checkpoint_hpc/${stem}_hpc"
