#!/bin/bash

# Kalantar ROUND 12 -- OG-T DRAINED PRELOAD.
#
#   cd /home/saeedvdi/links/projects/def-biaoli66/saeedvdi/projects/orca_4.0/Examples/Kalantar2025
#   sbatch submit_110_round12_hpc.sh
#
# WHY.  Round 11's own null found the cause of five rounds of OG-T failure, and it
# is not mechanical.  Over the 2 -> 55 s preload ramp the interface pore pressure
# rises 2.19 -> 51.08 MPa; with fault_pressure_coefficient = 1.0 that removes 46.7
# of the joint's 64.5 MPa of effective normal stress, so tau/tau_limit crosses 1.0
# at sigma_d = 57.6 MPa instead of holding to the experiment's 160.43 MPa.  Add
# alpha_f * p back and the total-stress slope is +0.277 on OG-T and +0.277 on
# OG-SH -- load reaches the joint correctly and always did.  Measured Skempton
# B = 0.914 against 0.930 predicted from the deck's own constants: the model is
# doing CORRECT UNDRAINED POROELASTICITY ON THE WRONG PROTOCOL.
#
# OG-SH does not show it because its 4.87 um fracture is 119 000x more transmissive
# in a_h^3 and drains the specimen as fast as the ramp loads it (dp/dsigma_d 0.017
# against OG-T's 0.372-0.416).  OG-T's 0.10 um fracture carries Q = 0.000 mL/min
# and cannot.  That 0.10 um is FAITHFUL to Kalantar's Table 2 -- the defect is the
# protocol, not the aperture.
#
# THE FIX.  Consolidation time is tau_c = L^2/c ~ 1.0e3 s (c = kM/mu = 1.5e-6 m^2/s,
# ~40 mm to the nearest port).  The parent ramps in 53 s, i.e. 5 % of ONE tau_c.
# These decks ramp over 9998 s (10 tau_c) and then HOLD 4000 s more at constant
# sigma_d before injection starts.  Nothing else changes.
#
# Array map:
#   0  OG-T  110_36_og_t_drained_preload_r12   THE GATE -- preload only, ~560 steps
#   1  OG-T  110_37_og_t_drained_full_r12      full 17-stage cycle on the same preload
#
# READING ORDER, AND IT MATTERS.  Read task 0 first and score it:
#
#     python3 scripts/score_110_round11.py \
#       Examples/Kalantar2025/OGT/results_csv_hpc/110_36_og_t_drained_preload_r12_hpc.csv
#
#   1. rise in interface_pressure_pp over the ramp        <= 3 MPa       [48.9 now]
#      3 MPa is not arbitrary. On the same pre-slip measure OG-SH sits at 3.46 MPa
#      and delivers ratio 0.999; OG-SC at 13.01 delivers 0.930; every OG-T deck is
#      at 23.7-36.6 and delivers 0.38-0.52. The scorer prints it as dp_MPa.
#   2. bb_effective_normal_stress_pp divided by
#      effective_normal_paper_frame_mpa_pp                >= 0.93        [0.277 now]
#   3. pre-slip slope d(sigma'_n)/d(sigma_d)              +0.22 +- 0.04  [-0.100 now]
#   4. tau/tau_limit at sigma_d = 160.43 MPa              < 1.0          [yields at 57.6]
#   5. cumulative_plastic_slip at end of preload          < 10 um        [0.5-2.4 mm now]
#
# IF TASK 0 FAILS, DISCARD TASK 1 -- do not analyse it.  Every OG-T validation datum
# in this campaign was taken from a specimen that had already yielded during its own
# preload, and task 1 would be one more of those.  The two are submitted together
# only to save an HPC round trip; that is scheduling, not a prediction that the gate
# passes.
#
# If Delta p falls but the ratio does not follow, the diagnosis is wrong and
# Doc/Memory/KALANTAR2025_ROUND11_BACKANALYSIS.md is what needs correcting.  If
# Delta p does not fall at all, the drainage path is blocked by something other than
# the aperture and the single-node ports are the next suspect.
#
# DO NOT SUBMIT ROUND-11 WAVE B (110_33 / 110_34 / 110_35).  All three were gated on
# 110_30, which failed all three of its criteria.
#
# Decks generated by scripts/make_110_round12_drained_preload.py; both Syntax OK.

#SBATCH --job-name=kalantar_110_r12
#SBATCH --chdir=/home/saeedvdi/links/projects/def-biaoli66/saeedvdi/projects/orca_4.0/Examples/Kalantar2025
#SBATCH --account=def-biaoli66
#SBATCH --time=1-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --mem=32G
#SBATCH --array=0-1
#SBATCH --output=kalantar_110_r12_%A_%a.out
#SBATCH --error=kalantar_110_r12_%A_%a.err

set -euo pipefail

project_root=/home/saeedvdi/links/projects/def-biaoli66/saeedvdi/projects/orca_4.0
study_root=${project_root}/Examples/Kalantar2025

case "${SLURM_ARRAY_TASK_ID}" in
  0) case_dir=OGT; stem=110_36_og_t_drained_preload_r12; keep_chk=false ;;
  1) case_dir=OGT; stem=110_37_og_t_drained_full_r12;    keep_chk=true  ;;
  *) echo "Unexpected SLURM_ARRAY_TASK_ID=${SLURM_ARRAY_TASK_ID}" >&2; exit 2 ;;
esac

ranks=32
case_path=${study_root}/${case_dir}
input_path=${case_path}/${stem}.i
executable=${project_root}/orca-opt

if [[ ! -f "${input_path}" ]]; then
  echo "Missing input deck: ${input_path}" >&2
  exit 3
fi

if [[ ! -x "${executable}" ]]; then
  echo "Missing or non-executable application: ${executable}" >&2
  exit 4
fi

cd "${case_path}"

# Alliance injects SLURM_MEM_PER_CPU; --mem sets SLURM_MEM_PER_NODE. Clear both.
unset SLURM_MEM_PER_NODE SLURM_MEM_PER_CPU SLURM_MEM_PER_GPU
mkdir -p results_csv_hpc results_exodus_hpc results_checkpoint_hpc logs

echo "Starting array task ${SLURM_ARRAY_TASK_ID}: ${case_dir}/${stem}.i"
echo "SLURM job ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}; ${ranks} ranks, 32G"

# Task 1 runs to t = 20745 s. Checkpoints are KEPT for it so a wall-clock timeout can
# be restarted -- the round-8 108-series lesson, where _nochk truncations could not be.
# Task 0 is ~560 steps and does not need them.
srun --mpi=pmi2 -n "${ranks}" "${executable}" -i "${stem}.i" \
  Outputs/chk/enable=${keep_chk} \
  csv_file_base="results_csv_hpc/${stem}_hpc" \
  exodus_file_base="results_exodus_hpc/${stem}_hpc" \
  checkpoint_file_base="results_checkpoint_hpc/${stem}_hpc"
