#!/usr/bin/env python3
"""Build full-cycle Kalantar 2025 Round-10 diagnostics.

Round 9 established the endpoints but did not close the mechanism test:

* b=0 completed to stage 5 and missed the slip/tau gates;
* b=0.006 reduced the RSF overstress in the desired direction but entered a
  timestep-cutback cascade at 408.189/2000 s, before it could be judged.

This builder inserts b=0.002 and b=0.004 without changing a, D_rs, V0, the
loading, mesh, or solver, and runs both through the complete OG-SH cycle. It
also expands the graded OG-T preload probe into a separately named full-cycle
deck. Existing generated outputs are overwritten only when they carry this
builder's marker.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KAL = ROOT / "Examples/Kalantar2025"
SH_PARENT = KAL / "OGSH/110_26_og_sh_rsf_a010_b006_r9.i"
OT_PROBE_PARENT = KAL / "OGT/110_23_og_t_graded_preload_r8.i"
OT_FULL_REFERENCE = KAL / "OGT/110_11_og_t_bbfast_r5.i"
OT_FULL_STEM = "110_29_og_t_graded_full_r10"
GENERATED = "GENERATED BY scripts/build_110_kalantar_round10_decks.py"


@dataclass(frozen=True)
class Arm:
    stem: str
    b_value: str


ARMS = (
    Arm("110_27_og_sh_rsf_a010_b002_r10", "0.002"),
    Arm("110_28_og_sh_rsf_a010_b004_r10", "0.004"),
)


def replace_assignment(text: str, key: str, value: str, note: str) -> str:
    pattern = re.compile(rf"^(?P<indent>\s*){re.escape(key)}\s*=\s*[^\n#]*(?:\s*#.*)?$", re.M)
    matches = list(pattern.finditer(text))
    if len(matches) != 1:
        raise RuntimeError(f"expected one active {key!r} assignment, found {len(matches)}")
    return pattern.sub(rf"\g<indent>{key} = {value}   # ROUND 10: {note}", text, count=1)


def output_bases(text: str, stem: str) -> str:
    for key, folder in (
        ("exodus_file_base", "results_exodus_hpc"),
        ("csv_file_base", "results_csv_hpc"),
        ("checkpoint_file_base", "results_checkpoint_hpc"),
    ):
        text = replace_assignment(text, key, f"{folder}/{stem}_hpc", "self-named output")
    return text


def assignment_value(text: str, key: str) -> str:
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=\s*(?P<value>[^\n#]+)", re.M)
    matches = pattern.findall(text)
    if len(matches) != 1:
        raise RuntimeError(f"expected one active {key!r} assignment, found {len(matches)}")
    return matches[0].strip()


def replace_literal_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one {label}, found {count}")
    return text.replace(old, new, 1)


def header(arm: Arm) -> str:
    return f"""# =============================================================================
# {arm.stem}
#
# {GENERATED}
# Parent: {SH_PARENT.name}
#
# KALANTAR ROUND 10 -- OG-SH RATE/STATE AGING BRACKET.
#
# ROUND-9 EVIDENCE. The b=0 direct-rate control reached stage 5 but missed both
# physical outcome gates: in-plane slip 25.244 um (target 30-60) and tau_5
# 22.081 MPa (target <=21.14). The b=0.006 aging arm stopped at 408.189/2000 s
# in a timestep-cutback cascade and is not physically interpretable.
#
# ONE CHANGE FROM THE b=0.006 ARM: rsf_b = {arm.b_value}. The physical direct
# effect a=0.010, D_rs=50 um, V0=5e-8 m/s, theta initialization, BB envelope,
# mesh, loading, and solver are held exactly. The requested full cycle continues
# through all nine Table 2 stages, including four unloading stages, to 3600 s.
#
# PASS: reach 3600 s without a cutback cascade; stage-5 in-plane slip 30-60 um;
# tau_5 <=21.14 MPa; no runaway; retain finite outputs through stage 9.
# Compare b=0, 0.002, 0.004, and 0.006 through the common stage-5 horizon.
# A monotone move toward both outcome gates identifies aging as useful. If both
# intermediate arms complete but miss the gates, aging alone is insufficient.
# If convergence fails at a reproducible b threshold, obtain the HPC nonlinear
# logs and investigate the RSF active-set/tangent before changing more physics.
# ============================================================================="""


def strip_round9_header(text: str) -> str:
    """Remove the generated Round-9 wrapper while retaining older deck history."""
    header_end = "# =============================================================================\n\n"
    if not text.startswith("# =============================================================================\n# 110_26_"):
        raise RuntimeError("Round-9 parent header has an unexpected form")
    end = text.find(header_end)
    if end < 0:
        raise RuntimeError("Round-9 parent header terminator not found")
    return text[end + len(header_end):]


def render(arm: Arm) -> str:
    text = strip_round9_header(SH_PARENT.read_text())
    text = replace_assignment(text, "rsf_b", arm.b_value, "aging-bracket value")
    text = replace_assignment(text, "end_time", "3600", "full nine-stage pressure cycle")
    text = output_bases(text, arm.stem)
    rendered = header(arm).rstrip() + "\n\n" + text
    return "\n".join(line.rstrip() for line in rendered.splitlines()) + "\n"


def write_arm(arm: Arm) -> Path:
    output = KAL / "OGSH" / f"{arm.stem}.i"
    if output.exists() and GENERATED not in output.read_text()[:3000]:
        raise RuntimeError(f"refusing to overwrite non-generated deck: {output}")
    output.write_text(render(arm))
    return output


def strip_probe_headers(text: str) -> str:
    """Remove the Round-8/probe wrappers and retain the underlying deck history."""
    marker = "# 93-SERIES -- MESH AND POSTPROCESSOR AUDIT FIXES."
    marker_pos = text.find(marker)
    if marker_pos < 0:
        raise RuntimeError("OG-T probe parent does not contain the 93-series marker")
    start = text.rfind("# =============================================================================\n", 0, marker_pos)
    if start < 0:
        raise RuntimeError("OG-T underlying-header separator not found")
    return text[start:]


def ot_header() -> str:
    return f"""# =============================================================================
# {OT_FULL_STEM}
#
# {GENERATED}
# Parent: {OT_PROBE_PARENT.name}
# Full-schedule reference: {OT_FULL_REFERENCE.name}
#
# KALANTAR ROUND 10 -- OG-T GRADED-MESH FULL CYCLE.
#
# The Round-8 graded-mesh diagnostic is extended from its 60-s preload horizon
# through all 17 Table 2 stages (nine loading, eight unloading) to 6800 s. The
# graded mesh, exact source nodes, corrected frame, material model, boundary
# conditions, loading functions, event cap, and nonlinear controls are unchanged.
# Full-cycle time-segment limits and Exodus cadence are restored from 110_11.
#
# GATE: judge the first 60 s before interpreting the injection response. Passing
# requires zero cumulative plastic slip, positive constitutive/paper-frame normal-
# stress slope, and <=5% normal-stress disagreement. The full output is retained
# even if this gate fails, but downstream stages are then diagnostic, not scoreable.
# ============================================================================="""


def render_ot_full() -> str:
    text = strip_probe_headers(OT_PROBE_PARENT.read_text())
    reference = OT_FULL_REFERENCE.read_text()
    text = replace_assignment(text, "end_time", "6800", "full 17-stage pressure cycle")
    text = replace_assignment(
        text, "time_t", assignment_value(reference, "time_t"), "full-cycle segment times")
    text = replace_assignment(
        text, "time_dt", assignment_value(reference, "time_dt"), "full-cycle segment limits")
    text = replace_assignment(text, "dtmax", "5.0", "full-cycle segment limits govern")
    text = replace_literal_once(
        text, "time_step_interval = 1", "time_step_interval = 4",
        "probe Exodus time_step_interval")
    text = output_bases(text, OT_FULL_STEM)
    rendered = ot_header().rstrip() + "\n\n" + text
    return "\n".join(line.rstrip() for line in rendered.splitlines()) + "\n"


def write_ot_full() -> Path:
    output = KAL / "OGT" / f"{OT_FULL_STEM}.i"
    if output.exists() and GENERATED not in output.read_text()[:3000]:
        raise RuntimeError(f"refusing to overwrite non-generated deck: {output}")
    output.write_text(render_ot_full())
    return output


def verify(paths: tuple[Path, ...]) -> None:
    for path, arm in zip(paths, ARMS):
        text = path.read_text()
        required = (
            GENERATED,
            "type = OrcaBartonBandisRateStateHardening",
            "tangential_viscosity = 0.0",
            "rsf_a = 0.010",
            f"rsf_b = {arm.b_value}",
            "rsf_characteristic_slip = 5.0e-5",
            "rsf_reference_velocity = 5.0e-8",
            "end_time = 3600   # ROUND 10: full nine-stage pressure cycle",
        )
        for token in required:
            if token not in text:
                raise RuntimeError(f"{path.name}: missing {token}")
        if "THIS ARM: b=0.006" in text:
            raise RuntimeError(f"{path.name}: retained contradictory Round-9 header")
        for base in ("exodus_file_base", "csv_file_base", "checkpoint_file_base"):
            if not re.search(rf"^\s*{base}\s*=.*{re.escape(path.stem)}_hpc", text, re.M):
                raise RuntimeError(f"{path.name}: {base} is not self-named")


def verify_ot(path: Path) -> None:
    text = path.read_text()
    required = (
        GENERATED,
        "mesh_file = mesh/kalantar2025_og_t_theta28_graded.e",
        "end_time = 6800   # ROUND 10: full 17-stage pressure cycle",
        "6799.5 6800.0",
        "dtmax = 5.0   # ROUND 10: full-cycle segment limits govern",
        "time_step_interval = 4",
    )
    for token in required:
        if token not in text:
            raise RuntimeError(f"{path.name}: missing {token}")
    for stale in ("end_time = 60", "time_t  = '0.0 60.0'", "time_step_interval = 1"):
        if stale in text:
            raise RuntimeError(f"{path.name}: retained probe-only setting {stale}")
    for base in ("exodus_file_base", "csv_file_base", "checkpoint_file_base"):
        if not re.search(rf"^\s*{base}\s*=.*{re.escape(path.stem)}_hpc", text, re.M):
            raise RuntimeError(f"{path.name}: {base} is not self-named")


def main() -> int:
    sh_built = tuple(write_arm(arm) for arm in ARMS)
    ot_built = write_ot_full()
    verify(sh_built)
    verify_ot(ot_built)
    for path in (*sh_built, ot_built):
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
