#!/usr/bin/env python3
"""Build the bounded Kalantar 2025 round-9 mechanism diagnostics.

The round contains three newly generated inputs and reuses the still-pending
110_23 OG-T graded preload probe:

* 110_24 OG-SC: apply the paper's spatially uniform (Pi + Po)/2 pressure to
  mechanical fault traction, while retaining the solved local pressure for flow;
* 110_25 OG-SH: physical rate direct-effect control (a=0.010, b=0);
* 110_26 OG-SH: same direct effect plus Dieterich aging (a=0.010, b=0.006).

Each new deck stops at its preregistered diagnostic horizon. Existing outputs are
overwritten only when they contain this script's generated marker.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KAL = ROOT / "Examples/Kalantar2025"
GENERATED = "GENERATED BY scripts/build_110_kalantar_round9_decks.py"


@dataclass(frozen=True)
class Arm:
    parent: Path
    output: Path
    header: str
    transform: str


def replace_assignment(text: str, key: str, value: str, note: str) -> str:
    pattern = re.compile(rf"^(?P<indent>\s*){re.escape(key)}\s*=\s*[^\n#]*(?:\s*#.*)?$", re.M)
    matches = list(pattern.finditer(text))
    if len(matches) != 1:
        raise RuntimeError(f"expected one active {key!r} assignment, found {len(matches)}")
    return pattern.sub(rf"\g<indent>{key} = {value}   # ROUND 9: {note}", text, count=1)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one {label}, found {count}")
    return text.replace(old, new, 1)


def output_bases(text: str, stem: str) -> str:
    for key, folder in (
        ("exodus_file_base", "results_exodus_hpc"),
        ("csv_file_base", "results_csv_hpc"),
        ("checkpoint_file_base", "results_checkpoint_hpc"),
    ):
        text = replace_assignment(text, key, f"{folder}/{stem}_hpc", "self-named output")
    return text


def header(stem: str, parent: Path, body: str) -> str:
    return f"""# =============================================================================
# {stem}
#
# {GENERATED}
# Parent: {parent.name}
#
{body.rstrip()}
# ============================================================================="""


def build_sc_paper_mean(arm: Arm, text: str) -> str:
    """Use the same (Pi+Po)/2 pressure definition as the paper's stress reduction."""
    pressure_function = """  # ROUND 9: pressure used only by mechanical fault traction.
  # Table 2 reduces effective normal stress with Pp=(Pi+Po)/2. Supplying that
  # same spatially uniform pressure here tests pressure-definition consistency
  # without an empirical fault_pressure_coefficient. The solved local pressure
  # remains untouched in czm_pressure and in the fracture-flow operator.
  [paper_mean_pressure_fn]
    type = ParsedFunction
    expression = '0.5 * (pin + ${production_pressure})'
    symbol_names = pin
    symbol_values = injection_pressure
  []

"""
    text = replace_once(
        text,
        "  [production_pressure_fn]\n",
        pressure_function + "  [production_pressure_fn]\n",
        "production-pressure function anchor",
    )

    pressure_material = """  [czm_paper_mean_pressure]
    type = ADGenericFunctionMaterial
    boundary = fracture_interface
    prop_names = paper_mean_interface_pressure
    prop_values = paper_mean_pressure_fn
  []
"""
    text = replace_once(
        text,
        "  [czm_contact]\n",
        pressure_material + "  [czm_contact]\n",
        "CZM contact material anchor",
    )

    # All three displacement components must consume the same pressure property.
    old = "    displacements = 'disp_x disp_y disp_z'\n    pressure_traction_coefficient = -${fault_pressure_coefficient}"
    new = (
        "    displacements = 'disp_x disp_y disp_z'\n"
        "    pore_pressure_property_name = paper_mean_interface_pressure\n"
        "    pressure_traction_coefficient = -${fault_pressure_coefficient}"
    )
    if text.count(old) != 3:
        raise RuntimeError(f"expected three fault-pressure kernels, found {text.count(old)}")
    text = text.replace(old, new)

    pressure_pp = """  [paper_mean_pressure_pp]
    type = ADSideAverageMaterialProperty
    property = paper_mean_interface_pressure
    boundary = fracture_interface
  []
"""
    text = replace_once(
        text,
        "  [interface_pressure_pp]\n",
        pressure_pp + "  [interface_pressure_pp]\n",
        "interface-pressure postprocessor anchor",
    )
    text = replace_assignment(text, "end_time", "4900", "stop after pressurization stage 7")
    return text


def build_sh_rsf(arm: Arm, text: str, b_value: str, label: str) -> str:
    """Replace the fitted linear viscosity with a bounded physical RSF test."""
    text = replace_once(
        text,
        "    type = OrcaBartonBandisContactTractionFastADHardening",
        "    type = OrcaBartonBandisRateStateHardening",
        "OG-SH contact material type",
    )
    rsf = f"""    tangential_viscosity = 0.0   # ROUND 9: RSF replaces the linear Perzyna term
    # Physical granite direct effect. V0=5e-8 m/s is the observed order of
    # 30 um per 600-s hold; D_rs=50 um is comparable to the measured stage-5 slip.
    use_rate_and_state = true
    rsf_a = 0.010
    rsf_b = {b_value}   # ROUND 9: {label}
    rsf_characteristic_slip = 5.0e-5
    rsf_reference_velocity = 5.0e-8
    rsf_theta0 = 0.0
"""
    pattern = re.compile(r"^\s*tangential_viscosity\s*=\s*[^\n]+\n", re.M)
    text, count = pattern.subn(rsf, text, count=1)
    if count != 1:
        raise RuntimeError("expected one tangential_viscosity assignment")

    rsf_pp = """  [rsf_theta_pp]
    type = SideAverageMaterialProperty
    property = rate_state_theta
    boundary = fracture_interface
  []
  [rsf_slip_velocity_pp]
    type = SideAverageMaterialProperty
    property = rate_state_slip_velocity
    boundary = fracture_interface
  []
  [rsf_overstress_pa_pp]
    type = SideAverageMaterialProperty
    property = rate_state_overstress
    boundary = fracture_interface
  []
  [rsf_overstress_mpa_pp]
    type = ParsedPostprocessor
    pp_names = rsf_overstress_pa_pp
    expression = 'rsf_overstress_pa_pp * 1e-6'
  []
"""
    text = replace_once(
        text,
        "  [fracture_interface_area_pp]\n",
        rsf_pp + "  [fracture_interface_area_pp]\n",
        "fracture-area postprocessor anchor",
    )
    text = replace_assignment(text, "end_time", "2000", "stop after pressurization stage 5")
    return text


def arms() -> tuple[Arm, ...]:
    sc_parent = KAL / "OGSC/110_12_og_sc_bbfast_r5.i"
    sh_parent = KAL / "OGSH/110_13_og_sh_bbfast_r6.i"

    sc_stem = "110_24_og_sc_papermean_r9"
    sc_body = """# KALANTAR ROUND 9 -- OG-SC PRESSURE-DEFINITION TEST.
# ONE MECHANISM CHANGE: mechanical fault traction uses the paper's uniform
# Pp=(Pi+Po)/2 pressure at coefficient 1.0. The hydraulic solve and its local
# interface pressure are unchanged. This replaces the fitted 0.80/0.84 factors
# with a directly testable pressure definition and stops at stage 7 (t=4900 s).
#
# PASS: <=2 um cumulative plastic slip through stage 6; stage-7 plastic-slip
# increment >10 um; stage-7 in-plane slip 18-28 um; tau_6=12.95+/-0.25 MPa;
# a_h6=1.50-1.70 um. Promote to 9100 s only if every gate passes."""

    sh_common = """# KALANTAR ROUND 9 -- OG-SH RATE/STATE MECHANISM TEST.
# The completed round-6 deck is held except that its fitted linear Perzyna
# viscosity is replaced by the existing Dieterich-Ruina overstress subclass.
# a=0.010 is inside the documented laboratory range for granite. V0=5e-8 m/s
# corresponds to 30 um per 600-s hold and D_rs=50 um is the observed slip scale.
# Diagnostic horizon: stage 5 (t=2000 s).
#
# PASS: stage-5 in-plane slip 30-60 um; tau_5<=21.14 MPa; no runaway. The b=0
# arm is the direct-rate control. Improvement unique to b=0.006 identifies aging
# state, rather than rate alone, as the missing mechanism."""

    return (
        Arm(
            parent=sc_parent,
            output=KAL / "OGSC" / f"{sc_stem}.i",
            header=header(sc_stem, sc_parent, sc_body),
            transform="sc_paper_mean",
        ),
        Arm(
            parent=sh_parent,
            output=KAL / "OGSH/110_25_og_sh_rsf_a010_b000_r9.i",
            header=header(
                "110_25_og_sh_rsf_a010_b000_r9", sh_parent,
                sh_common + "\n# THIS ARM: b=0.000, so it contains the direct rate effect but no state evolution effect.",
            ),
            transform="sh_b000",
        ),
        Arm(
            parent=sh_parent,
            output=KAL / "OGSH/110_26_og_sh_rsf_a010_b006_r9.i",
            header=header(
                "110_26_og_sh_rsf_a010_b006_r9", sh_parent,
                sh_common + "\n# THIS ARM: b=0.006 (velocity strengthening, a-b=+0.004) adds Dieterich aging.",
            ),
            transform="sh_b006",
        ),
    )


def write_arm(arm: Arm) -> Path:
    text = arm.parent.read_text()
    if arm.transform == "sc_paper_mean":
        text = build_sc_paper_mean(arm, text)
    elif arm.transform == "sh_b000":
        text = build_sh_rsf(arm, text, "0.000", "direct-rate control; no aging effect")
    elif arm.transform == "sh_b006":
        text = build_sh_rsf(arm, text, "0.006", "Dieterich aging effect")
    else:
        raise RuntimeError(f"unknown transform {arm.transform}")

    text = output_bases(text, arm.output.stem)
    rendered = arm.header.rstrip() + "\n\n" + text
    rendered = "\n".join(line.rstrip() for line in rendered.splitlines()) + "\n"
    if arm.output.exists() and GENERATED not in arm.output.read_text()[:3000]:
        raise RuntimeError(f"refusing to overwrite non-generated deck: {arm.output}")
    arm.output.write_text(rendered)
    return arm.output


def verify(paths: tuple[Path, ...]) -> None:
    for path in paths:
        text = path.read_text()
        if GENERATED not in text[:3000]:
            raise RuntimeError(f"{path.name}: generated marker missing")
        for base in ("exodus_file_base", "csv_file_base", "checkpoint_file_base"):
            if not re.search(rf"^\s*{base}\s*=.*{re.escape(path.stem)}_hpc", text, re.M):
                raise RuntimeError(f"{path.name}: {base} is not self-named")

    sc = paths[0].read_text()
    if sc.count("pore_pressure_property_name = paper_mean_interface_pressure") != 3:
        raise RuntimeError("OG-SC: all three pressure kernels must use paper mean pressure")
    if not re.search(r"^\s*end_time\s*=\s*4900(?:\s|#|$)", sc, re.M):
        raise RuntimeError("OG-SC: wrong diagnostic horizon")

    for path, b in zip(paths[1:], ("0.000", "0.006")):
        text = path.read_text()
        required = (
            "type = OrcaBartonBandisRateStateHardening",
            "tangential_viscosity = 0.0",
            "rsf_a = 0.010",
            f"rsf_b = {b}",
            "rsf_characteristic_slip = 5.0e-5",
            "rsf_reference_velocity = 5.0e-8",
        )
        for token in required:
            if token not in text:
                raise RuntimeError(f"{path.name}: missing {token}")


def main() -> int:
    built = tuple(write_arm(arm) for arm in arms())
    verify(built)
    for path in built:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
