#!/usr/bin/env python3
"""Build the bounded Kalantar 2025 Round-8 diagnostic decks.

This script deliberately does not rebuild the earlier 110-series estate.  It clones
the completed, audited parents and changes one diagnostic axis per arm:

* OG-SC: fault-pressure coupling, 0.80 and 0.84, through stage 7;
* OG-SH: slip-weakening exponent, 1.20 and 1.60, through stage 5;
* OG-T:  28-degree graded mesh, preload only, with mesh-consistent source nodes.

Run from any directory.  Existing outputs are overwritten only when they contain
this script's GENERATED marker.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
KAL = ROOT / "Examples/Kalantar2025"
GENERATED = "GENERATED BY scripts/build_110_kalantar_round8_decks.py"


@dataclass(frozen=True)
class Arm:
    parent: Path
    output: Path
    header: str
    assignments: tuple[tuple[str, str, str], ...]
    output_group: str = "hpc"


def replace_assignment(text: str, key: str, value: str, note: str) -> str:
    """Replace one active top-level or block assignment, retaining indentation."""
    pattern = re.compile(rf"^(?P<indent>\s*){re.escape(key)}\s*=\s*[^\n#]*(?:\s*#.*)?$", re.M)
    matches = list(pattern.finditer(text))
    if len(matches) != 1:
        raise RuntimeError(f"expected one active {key!r} assignment, found {len(matches)}")
    return pattern.sub(rf"\g<indent>{key} = {value}   # ROUND 8: {note}", text, count=1)


def replace_literal_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one {label}, found {count}")
    return text.replace(old, new, 1)


def output_bases(text: str, stem: str, group: str) -> str:
    directory = {
        "hpc": ("results_exodus_hpc", "results_csv_hpc", "results_checkpoint_hpc"),
        "probe": ("results_exodus_probe", "results_csv_probe", "results_checkpoint_probe"),
    }[group]
    for key, folder in zip(
        ("exodus_file_base", "csv_file_base", "checkpoint_file_base"), directory
    ):
        text = replace_assignment(text, key, f"{folder}/{stem}_hpc", "self-named output")
    return text


def write_arm(arm: Arm) -> Path:
    text = arm.parent.read_text()
    for key, value, note in arm.assignments:
        text = replace_assignment(text, key, value, note)

    # The graded OG-T mesh has different exact interface nodes.  Naming them avoids
    # use_closest_node silently choosing a mesh-dependent location.
    if arm.output.stem.startswith("110_23_"):
        text = replace_literal_once(
            text,
            "coord = '-0.020362222 0.0 0.011704230'",
            "coord = '-0.019819655172 0.0 0.012724650276'   # ROUND 8: exact graded-mesh interface node",
            "OG-T source_in coordinate",
        )
        text = replace_literal_once(
            text,
            "coord = '0.020362222 0.0 0.088295770'",
            "coord = '0.019819655172 0.0 0.087275349724'   # ROUND 8: exact graded-mesh interface node",
            "OG-T source_out coordinate",
        )

    text = output_bases(text, arm.output.stem, arm.output_group)
    rendered = arm.header.rstrip() + "\n\n" + text

    if arm.output.exists() and GENERATED not in arm.output.read_text()[:3000]:
        raise RuntimeError(f"refusing to overwrite non-generated deck: {arm.output}")
    arm.output.write_text(rendered)
    return arm.output


def header(stem: str, parent: Path, body: str) -> str:
    return f"""# =============================================================================
# {stem}
#
# {GENERATED}
# Parent: {parent.name}
#
{body.rstrip()}
# ============================================================================="""


def arms() -> tuple[Arm, ...]:
    sc_parent = KAL / "OGSC/110_12_og_sc_bbfast_r5.i"
    sh_parent = KAL / "OGSH/110_13_og_sh_bbfast_r6.i"
    ot_parent = KAL / "OGT/110_11_og_t_preload_probe.i"

    sc_common = """# KALANTAR ROUND 8 -- OG-SC PRESSURE-COUPLING BRACKET.
# ONE PHYSICS CHANGE: fault_pressure_coefficient.  Tangential viscosity stays at
# the Round-5 value because Round 6's 5x arm was numerically indistinguishable.
# The aperture law, peak/residual strength, frame, D_c, mesh and schedule are held.
# Diagnostic horizon: t=4900 s, the end of pressurization stage 7.
#
# WHY: before the premature stage-6 burst, the paper-frame normal stress is right
# but the interface law sees 2.09 MPa less compression at stage 5 and 3.52 MPa less
# at stage 6.  The gap follows the difference between area-mean fracture pressure
# and the paper's (P_i+P_o)/2 approximation.  The 0.80/0.84 arms bracket the
# least-squares alignment coefficient (0.81 through stage 7; 0.84 through stage 5).
#
# PASS: <=2 um plastic slip through stages 5-6; macroscopic slip at stage 7;
# stage-7 in-plane slip 18-28 um; tau_6 near 12.95 MPa; a_h6=1.50-1.70 um.
# INTERPRETATION: this is an inferred pressure-averaging/effective-coupling factor,
# not a measured rock Biot coefficient.  Promote only a passing arm to 9100 s."""

    sh_common = """# KALANTAR ROUND 8 -- OG-SH WEAKENING-SHAPE BRACKET.
# ONE PHYSICS CHANGE: slip_weakening_exponent.  D_c remains 100 um on the verified
# corrected frame; all strength endpoints, hydraulics, mesh and schedule are held.
# Diagnostic horizon: t=2000 s, the end of pressurization stage 5.
#
# WHY: D_c=150 -> 100 um improved mean nRMSE 21.87 -> 19.06, but stage-5 slip is
# still 27.4 vs 44.6 um and tau is 21.90 vs 19.57 MPa.  The preregistered D_c gate
# says not to sweep D_c again when the 100-um arm stays below 30 um.  The exponent
# tests early weakening shape without moving the calibrated peak/residual endpoints.
#
# PASS: stage-5 slip 30-60 um, tau_5 <=21.14 MPa, and no runaway.  Extend only a
# passing arm through unloading; if neither arm passes, close scalar shear tuning."""

    ot_body = """# KALANTAR ROUND 8 -- OG-T MESH-RESOLUTION PRELOAD FALSIFIER.
# ONE DIAGNOSTIC CHANGE: the corrected-frame, displacement-controlled 28-degree
# preload probe uses kalantar2025_og_t_theta28_graded.e.  Material parameters,
# boundary conditions, loading history and 60-s horizon are held.  The two source
# coordinates are moved only to the exact interface nodes belonging to this mesh.
# Exodus remains every timestep for the fracture-tip field audit.
#
# PASS BEFORE ANY FULL OG-T RUN: zero cumulative plastic slip; positive slope of
# constitutive versus paper-frame normal stress; normal-stress agreement within 5%.
# If the negative slope persists, mesh resolution is falsified and the next action
# is a localized fracture-tip/contact representation study, not material tuning."""

    specs = (
        ("110_19_og_sc_pcoeff0p80_r8", sc_parent, sc_common, (("fault_pressure_coefficient", "0.80", "lower pressure-coupling arm"), ("end_time", "4900", "stop after stage 7")), "hpc"),
        ("110_20_og_sc_pcoeff0p84_r8", sc_parent, sc_common, (("fault_pressure_coefficient", "0.84", "upper pressure-coupling arm"), ("end_time", "4900", "stop after stage 7")), "hpc"),
        ("110_21_og_sh_swexp1p20_r8", sh_parent, sh_common, (("slip_weakening_exponent", "1.20", "faster early-weakening arm"), ("end_time", "2000", "stop after stage 5")), "hpc"),
        ("110_22_og_sh_swexp1p60_r8", sh_parent, sh_common, (("slip_weakening_exponent", "1.60", "slower control arm"), ("end_time", "2000", "stop after stage 5")), "hpc"),
        ("110_23_og_t_graded_preload_r8", ot_parent, ot_body, (("mesh_file", "mesh/kalantar2025_og_t_theta28_graded.e", "graded 28-degree mesh"),), "probe"),
    )

    out = []
    for stem, parent, body, assignments, group in specs:
        folder = "OGSC" if "og_sc" in stem else "OGSH" if "og_sh" in stem else "OGT"
        out.append(
            Arm(
                parent=parent,
                output=KAL / folder / f"{stem}.i",
                header=header(stem, parent, body),
                assignments=assignments,
                output_group=group,
            )
        )
    return tuple(out)


def verify(paths: tuple[Path, ...]) -> None:
    expected = {
        "110_19": ("fault_pressure_coefficient", "0.80", "end_time", "4900"),
        "110_20": ("fault_pressure_coefficient", "0.84", "end_time", "4900"),
        "110_21": ("slip_weakening_exponent", "1.20", "end_time", "2000"),
        "110_22": ("slip_weakening_exponent", "1.60", "end_time", "2000"),
        "110_23": ("mesh_file", "mesh/kalantar2025_og_t_theta28_graded.e", "end_time", "60"),
    }
    for path in paths:
        text = path.read_text()
        prefix = path.stem.split("_", 2)[:2]
        key = "_".join(prefix)
        a, av, b, bv = expected[key]
        for name, value in ((a, av), (b, bv)):
            pattern = rf"^\s*{re.escape(name)}\s*=\s*{re.escape(value)}(?:\s|#|$)"
            if not re.search(pattern, text, re.M):
                raise RuntimeError(f"{path.name}: missing {name}={value}")
        for base in ("exodus_file_base", "csv_file_base", "checkpoint_file_base"):
            if not re.search(rf"^\s*{base}\s*=.*{re.escape(path.stem)}_hpc", text, re.M):
                raise RuntimeError(f"{path.name}: {base} is not self-named")


def main() -> int:
    built = tuple(write_arm(arm) for arm in arms())
    verify(built)
    for path in built:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
