"""Is Table 2's (sigma'_n, tau) pair generated by ONE differential stress?

Ye & Ghassemi eq (3)-(4):
    sigma'_n = (sigma3 - Pbar) + sigma_d sin^2(theta)
    tau      =                   sigma_d sin(theta)cos(theta)
so   sigma'_n = sigma3 - Pbar + tau * tan(theta),  Pbar = (Pi + Po)/2.
Two unknowns per specimen: theta and Po (sigma3 = 30 MPa given).
Fit them by least squares over all 11 stages and look at the residual.
"""
import sys, numpy as np
from pathlib import Path
ROOT=Path("/media/geomechanics/Data4TB/projects/orca_4.0"); sys.path.insert(0,str(ROOT/"scripts"))
import table2_gate as G
T2=G.TABLE2
PI=np.array(G.PI_TARGETS,dtype=float)
print(f"{'specimen':<10}{'fitted theta':>14}{'fitted Po MPa':>15}{'max|resid| MPa':>17}{'deck theta':>13}")
DECK={"SWT1":32.0,"SWT2":30.0,"SWS3":29.0,"SWS4":30.0}
for s in ["SWT1","SWT2","SWS3","SWS4"]:
    sn=np.asarray(T2[s]["sigma_n_MPa"],float); ta=np.asarray(T2[s]["tau_MPa"],float)
    # sn = 30 - 0.5*Pi - 0.5*Po + tan(th)*ta   ->  y = A*[tan(th), -0.5*Po]
    y = sn - 30.0 + 0.5*PI
    A = np.column_stack([ta, np.ones_like(ta)])
    coef,*_ = np.linalg.lstsq(A,y,rcond=None)
    tan_th, c = coef
    th=np.degrees(np.arctan(tan_th)); Po=-2.0*c
    r=y-A@coef
    print(f"{s:<10}{th:>14.3f}{Po:>15.3f}{np.abs(r).max():>17.5f}{DECK[s]:>13.1f}")
print()
print("PI targets:", PI)
