# =============================================================================
# 110_21_og_sh_swexp1p20_r8
#
# GENERATED BY scripts/build_110_kalantar_round8_decks.py
# Parent: 110_13_og_sh_bbfast_r6.i
#
# KALANTAR ROUND 8 -- OG-SH WEAKENING-SHAPE BRACKET.
# ONE PHYSICS CHANGE: slip_weakening_exponent.  D_c remains 100 um on the verified
# corrected frame; all strength endpoints, hydraulics, mesh and schedule are held.
# Diagnostic horizon: t=2000 s, the end of pressurization stage 5.
#
# WHY: D_c=150 -> 100 um improved mean nRMSE 21.87 -> 19.06, but stage-5 slip is
# still 27.4 vs 44.6 um and tau is 21.90 vs 19.57 MPa.  The preregistered D_c gate
# says not to sweep D_c again when the 100-um arm stays below 30 um.  The exponent
# tests early weakening shape without moving the calibrated peak/residual endpoints.
#
# PASS: stage-5 slip 30-60 um, tau_5 <=21.14 MPa, and no runaway.  Extend only a
# passing arm through unloading; if neither arm passes, close scalar shear tuning.
# =============================================================================

# =============================================================================
# 110_13_og_sh_bbfast_r6
#
# KALANTAR ET AL. (2025), specimen OG-SH (shear fracture) -- ROUND 6.
# Built by scripts/build_110_kalantar_decks.py from
# Examples/YeGhasemmi2018/SWT2/93_03_swt2_final_theta30_resc9p71_ppfix.i.
#
# WHAT CHANGED FROM ROUND 5 (doc/KALANTAR2025_ROUND5_BACKANALYSIS.md)
#   OG-SH: corrected-frame D_c bracket, 150 -> 100 um.  Round 5 verified the
#   stiffness mechanism (84 -> 165 MPa/mm within-run, expected 172), but its outcome
#   overshot: stage-5 slip 23.18 vs 44.6 um and tau +14.9 %.  This is the first D_c
#   arm evaluated on the corrected frame; all other constants are held.
#   NULL: stage-5 slip = 45 +/- 15 um and tau error falls below +8 %.
#
# WHAT CHANGED FROM ROUND 4 (doc/KALANTAR2025_ROUND4_BACKANALYSIS.md)
#   ROUND 5 CHANGES ONE THING: THE FRAME. Round 4's four constants produced a split
#   verdict -- OG-SC's aperture null PASSED (a_h 1.53 against a preregistered
#   1.60 +/- 0.10; that channel went 39 -> 10 nRMSE) while OG-SH got worse, 17 -> 31.
#   Chasing that failure found a defect upstream of every constitutive constant.
#
#   THE JOINT WAS UNLOADING AGAINST 0.59x THE EXPERIMENT'S STIFFNESS. The axial BC is
#   a penalty spring of K_sys/A backed by an elastic core, and the two are in SERIES,
#   so the stiffness the joint sees is 1/(1/penalty + C_ax). Measured across the
#   round-3/round-4 pair -- which differ in D_c alone -- OG-SH's tau shed 82.5 MPa per
#   mm of slip; K_sys/A predicts 150.5 and the series value predicts 88.8. An 8 %
#   match to the series value.
#
#   Table 2's own dL_s/dtau identity verifies with K_sys ALONE to 0.4-4 % on all three
#   specimens, so the paper's K_sys is the whole loading SYSTEM, sample included. The
#   deck was counting the sample twice. Inverted: penalty = 1/(A/K_sys - C_ax), which
#   is 3.27x on OG-SH and 2.37x on the other two, to raise the stiffness the JOINT
#   sees by 1.695x and 1.579x. Those two ratios are different; do not confuse them.
#
#   CONSEQUENCE FOR EVERY CAP THIS CAMPAIGN HAS QUOTED: they used the machine-only
#   k_eff and are all 1.7x too small.
#
#   AND OG-SH's D_c GOES BACK TO 150 um. Round 4 fitted it to Table 2's mu(s) path
#   (59.3 um) and slip went +15 % -> +155 %, tau +9.7 % -> -19.6 %. The fit treated
#   dL_s as an independent variable when the model has to SOLVE for it: shorter D_c ->
#   weaker joint -> more slip -> weaker still. Interpolating the two runs splits (tau
#   wants 110 um, slip 166), and a split means a second defect -- the frame. D_c is not
#   re-bracketable against a soft frame, so it is reverted and held.
#
#   OG-SC keeps all three of its round-4 constants: the residual recovered two thirds
#   of its post-burst gap and the aperture pair passed its null outright.
#
# WHAT CHANGED IN ROUND 4 (doc/KALANTAR2025_ROUND3_BACKANALYSIS.md, Part II)
#   Round 3 completed on OG-SH and OG-SC. OG-SH went 62 -> 67 -> 17 mean nRMSE, by
#   acting on ONE preregistered null. FOUR constants move in round 4, all on the two
#   scoreable specimens, and everything else is held so the round stays attributable.
#
#   A. The SLIP-WEAKENING RESIDUAL is now read where the joint is sliding. Rounds 2-3
#      used atan(tau/sigma'_n) at Table 2's LAST stage on every specimen. On OG-SC
#      that stage is LOCKED -- dL_s has not moved since stage 10 -- and a locked joint
#      sits BELOW its limit, so the number was a lower bound, not a measurement. It
#      read 15.354 deg against a true 21.175, and the run collapsed to tau = 4.85 MPa
#      where Table 2 says 9.73. This deck: 25.930 deg.
#   B. D_c is FITTED to Table 2's own mu(s) path, not guessed from the stability cap.
#      OG-SH's 150 um delivered 18 % of the measured strength drop at the measured
#      slip. Fitted on the sliding stages it is 59.3 um. Where Table 2 has too few
#      sliding stages to resolve it (OG-SC has one), D_c is HELD, not fitted to a
#      single point.
#   C. The STABILITY CAP was 1.36x too strict and it was blocking B. `D_c < dtau/k_eff`
#      assumes a LINEAR drop over D_c; the law is exp(-(s/D)^1.4), whose steepest slope
#      is 0.7355 (mu_p-mu_r)/D. It also charged the WHOLE tau drop to friction when
#      sigma'_n falling under injection supplies a third of it. The cap is now REPORTED
#      rather than asserted: it is a linearised criterion and the fitted path is a
#      direct measurement, so when they disagree the measurement wins.
#   D. NORMAL CLOSURE is fitted where it is identifiable. V_m and K_ni were inherited
#      Ye2018 fits with sigma_0 = V_m K_ni = 15 MPa, BELOW OG-SC's 28.5-36.1 MPa range,
#      so g(s) = s^p/(sigma_0^p+s^p) never left 0.93-0.97 and the closure term could
#      deliver 0.051 um against a measured 0.570. Fitted only on stages whose slip is
#      at print resolution -- the only ones where a_h moves for a single reason.
#   E. use_mobilized_jrc STAYS FALSE. Round 3 closed the standing question of why
#      bb_jrc_mobilized never moves: the flag is off in every deck of both campaigns.
#      Turning it on is not a fix -- jrc = JRC sbar^n ramps roughness UP with slip.
#      The weakening these decks run is use_roughness_degradation plus slip weakening,
#      and both are live (roughness_state 1.000 -> 0.732 on OG-SH).
#
# WHAT CHANGED FROM ROUND 2 (see Examples/Kalantar2025/MEMORY.md sections 6.7-6.11)
#   1. TIME STEPPING. dtmax 0.75 -> per-segment time_t/time_dt, 1.5 s on ramps and
#      5.0 s in holds, snapped onto every injection breakpoint. 4800 forced steps
#      -> 1140. This, not the mesh, is what truncated OG-T at 36 % and OG-SC at 77 %.
#   2. FLOW GEOMETRY. paper_/mesh_flow_width_over_length are now really substituted
#      (0.606072 / 0.606012); round 2's regex needed a suffix only the SW-S3
#      parent had, so OG-SH and OG-T kept Ye2018's and OG-SH's SCORED Q ran 1.342x high.
#   3. ENVELOPE, per specimen and NOT in the same direction -- see below.
#   The mesh is deliberately UNCHANGED. Coarsening OG-SH to factor 4 puts both
#   injection points on BULK nodes ~950 um off the fracture and lengthens the flow
#   path 2.94 %; and a discretisation change in the same round as the physics fixes
#   would make neither attributable.
#
# NOTHING IN THIS DECK IS CALIBRATED. Every constant below is derived from the
# paper, from Table 2, or measured off the verified mesh. The parent supplies
# structure only. What is still INHERITED and therefore still suspect is listed
# at the bottom.
#
# DERIVED CONSTANTS
#   theta            29.0 deg  (Table 1)
#   sigma_3          33.00 MPa  RECOVERED from Table 2 by the angle identity. The
#                    prose says 30 MPa; that is the EFFECTIVE confining pressure.
#                    Using 30 here would be a 10 % error on every stage.
#   E, nu            63 GPa, 0.16  (section 2.1)
#   porosity, k      0.0033, 1.4e-20 m^2  (section 2.1)
#   JRC, JCS         15.60, 153 MPa (= UCS, section 2.1 / 3.2)
#   peak envelope    pinned through Table 2 stage 1 (sigma'_n 42.99, tau 26.14 MPa)
#                    -> phi_peak 30.12 deg at the stage-1 sigma'_n of
#                    42.99 MPa, so phi_r = phi_peak - JRC log10(JCS/sigma'_n)
#                    = 21.519 deg. tau_limit there = 26.14 MPa.
#                    ROUND 3: PINNED through Table 2 stage 1, not read off
#                    Figure 3. Section 4.1 has this joint creeping through every
#                    hold, so its stage-1 pair IS on the envelope:
#                    tau_limit(42.99) = 26.14 MPa vs Table 2's
#                    26.14. Round 2 ran 32.70 deg and stalled at
#                    tau/tau_limit = 0.9900 with JRC pinned all run.
#   residual         phi = 25.930 deg from Table 2 stage 9
#                    (tau 18.97 / sigma'_n 39.02 MPa).
#                    BOUNDED, not measured: this joint is still weakening when the test ends. Lowest mobilised friction is Table 2 stage 9; the upper bound is 28.979 deg from the last sliding stage 6
#                    Upper bound from the last sliding stage: 28.979 deg.
#                    Round 1 carried the parent's 29.756 deg here, which on OG-SH was
#                    ABOVE phi_r and made the joint STRENGTHEN with slip.
#   dilation         4.300 deg = 0.5 JRC log10(JCS/sigma'_n), Barton's peak
#                    dilation. The parent's value was a Ye2018 fit (13.97 deg).
#   D_c              100.0 um -- HELD at round 3's value, round-6 corrected-frame bracket arm: round 5 at 150 um under-slipped (23.18 vs 44.6 um at stage 5) and over-carried tau (+14.9%); 100 um tests the coupled response without conditioning the law on model-predicted slip.
#                    Stick-slip cap 20.9 um = 0.7355 * dtau_friction / k_eff,
#                    k_eff = K_sys cos^2 theta sin theta / A = 0.1505 MPa/um.
#                    The naive cap (linear drop, whole tau drop charged to friction)
#                    would read 47.7 um -- see item C above. D_c > cap -> STABLE, which is what the paper reports.
#   aperture         a_h0 4.87 um anchored at sigma'_n 42.99 MPa
#                    (Table 2 stage 1); bounds [0.744, 14.61] um bracket
#                    Table 2's observed [3.72, 4.87] um.
#                    slip_damage_scale 1.15 um.
#   K_sys            796 kN/mm MEASURED (section 2.3) -> penalty 1.328e+12 Pa/m.
#                    This is the constant whose x2 bracket moved Q by -94/+408 % on
#                    Ye2018 and had to be inferred there. Here it is data.
#   W/L              0.60607 paper / 0.60601 mesh.
#                    Eq (7) as printed misses the paper's own Table 2 by 10.3x in
#                    a_h^3; the plain cubic law reproduces it to 0.5 %. See
#                    scripts/kalantar_parameter_audit.py section 8.
#
# SCHEDULE (section 2.3, cross-checked against Table 2's stage count)
#   3 MPa steps at 0.03 MPa/s, held 300 s, up to 18 MPa
#   (5 stages), then back down to 6 MPa (4 stages). end_time 3600 s.
#   Outlet held at 3 MPa throughout.
#
# WHAT WAS DELIBERATELY NOT INHERITED
#   fault_pressure_coefficient -> 1.0, and poro_du / axial_relax_du /
#   side_unload_relax_pressure -> 0. Those are fitted Ye2018 load-path knobs for a
#   different specimen set on a different frame. Importing them would be silent
#   contamination of a validation that is supposed to be independent.
#
# THE AXIAL GATE
#   axial_pres_final is a SERIES-SPRING solve, not -sigma_1/penalty. The penalty BC
#   delivers sigma_1 = penalty*(u_cmd - u_sample), so the core's own shortening has
#   to be added back: u_cmd = sigma_1/penalty + C_ax*(sigma_1-sigma_3) with C_ax =
#   1.7118e-12 m/Pa (0.8987 L/E, calibrated on the completed OG-SH run 19444645).
#   Target sigma_1 = 94.65 MPa from Table 2 stage 1 via tau = (sigma_1-sigma_3)
#   sin theta cos theta. Still worth a 200 s check against the stage-1 target:
#   tau = 26.14 MPa, sigma'_n = 42.99 MPa.
#
# THE REPORTING FRAME (round 1 got all of this wrong)
#   differential_stress_reaction_mpa_pp subtracts sigma_3 = 33.0, not Ye2018's 30.
#   effective_normal_paper_frame uses sin^2(29.0) = 0.235040.
#   shear_stress_paper_frame uses sin cos(29.0) = 0.424024.
#   The 4 bulk-gauge PointValues span a 90 mm chord about z = 0.0600 m, the
#   REAL core mid-height. Round 1 used the PARENT's, which put two of them outside
#   the OG-T and OG-SC meshes and killed both jobs at t = 0.75 s.
#
# WHAT IS STILL INHERITED AND STILL SUSPECT (round-6 candidates)
#   initial_normal_stiffness, maximum_closure, normal_closure_*,
#   normal_unload_retention_fraction, aperture_scale,
#   roughness_characteristic_slip and dilation_decay_distance are all Ye2018 fits.
#
#   ROUND 4 removed two of these on OG-SC. The claim that "at Kalantar's stress levels
#   the closure term is nearly inert, ~0.03 um" was written as a reason not to bother
#   and turned out to be the whole aperture defect: OG-SC's measured a_h swings 0.570
#   um and the saturated law could deliver 0.051. INERT IS NOT THE SAME AS HARMLESS --
#   a term pinned near its ceiling does not merely contribute little, it cannot respond
#   at all. V_m and K_ni are now fitted here -- but NOT on this specimen, whose closure and gouge terms are confounded (it slips through its own pressurization branch), so its pair is still the parent s.
#
#   tangential_viscosity is not a numerical regulariser; it is the hidden rate law.
#   It remains inherited on OG-SH/OG-T.  OG-SC round 6 prices it explicitly at 5x
#   because the corrected-frame run still accumulated 3.75 um before its early burst.
#
# PREDICTIONS FOR ROUND 4, WRITTEN BEFORE THE RUN
#   ONE NUMBER EACH, so none can be read two ways. This is the practice that paid off
#   in round 3: round 2 closed by naming a single null, round 3 acted on it, and
#   OG-SH's mean nRMSE went 67 -> 17. Round 2's own prediction had offered a two-branch
#   falsifier whose true cause was in neither branch, and it sent the post-mortem at a
#   gate that had just passed.
#
#   OG-SH, on D_c 150 -> 59.3 um:
#     tau error at stage 9 falls from +9.7 % to between +3 % and +7 %.
#
#   The band is not hedging -- it is the honest consequence of a defect this change
#   does NOT address. sigma'_n runs +2.6 % high on the unloading branch, and at the
#   measured mu of 0.4863 that alone puts tau +2.6 % high no matter what the friction
#   law does. So: if the error lands in the band, the friction law is finished on this
#   specimen and the remainder is the sigma'_n bias -- attack that next, not D_c.
#   IF IT LANDS BELOW +3 %, two errors have cancelled and neither is closed.
#   IF IT STAYS ABOVE +7 %, D_c is not the mechanism and the fit is wrong.
# =============================================================================
# =============================================================================
# 93-SERIES -- MESH AND POSTPROCESSOR AUDIT FIXES.  SW-T2 mesh 5
# Built from 91_04_swt2_bbfast_theta30_resc9p71_kernel_SV_biot0p6.i.  Constitutive parameters are UNCHANGED;
# this series changes only what is measured and reported, plus one source-node
# coordinate on SW-T1 mesh-5.
#
# WHAT MOVED IN THIS DECK
#   1. TWENTY DIAGNOSTIC CHANNELS ADDED (task #82).  SW-S4 carried 87
#      postprocessors and the other three carried 70; the eight bb_* envelope
#      channels, the five loading-frame channels and the seven bulk_* kinematic
#      channels existed only there.  All eight 93-series decks now emit the same
#      91.  None of them feeds the Table-2 gate.
#      bulk_sin_theta / bulk_cos_theta are set from THIS specimen's own theta
#      (30.0 deg), not copied from SW-S4.
#
# WHAT DID NOT MOVE, ON ANY 93-SERIES DECK
#   - every constitutive parameter of [czm_contact];
#   - the mesh file, the injection schedule, the BCs, the solver;
#   - the paper-frame trig constants (each already matched its own mesh's theta
#     to four decimals -- verified against the Exodus fracture_interface nodeset).
# =============================================================================
# =============================================================================================
# 93_03_swt2_final_theta30_resc9p71_ppfix
#
# 91-SERIES: fix the RESIDUAL, keep the ONSET.  Back-analysis of the 90-series, 2026-08-17.
#
# Parent: 90_03_swt2_bbfast_theta30_cohesion_c33p2_kernel_SV_biot0p6.i
#
# WHAT THE 90-SERIES SETTLED.  The level correction worked.  Every deck that was given more peak
# strength moved its margin crossing to the top of the staircase and its onset onto the measured
# event:
#
#     specimen  case    crosses 0 at   slip onset (sim vs val)   mean nRMSE (corrected sigma_d)
#     SW-T1     90_01   24->25 MPa     1610 vs 1650-1725 s        10.6%
#     SW-T1     90_02   never          locked                     51.3%
#     SW-T2     90_03   24->25 MPa     2220 vs 2225-2255 s         6.3%
#     SW-T2     90_04   never          locked                     37.7%
#     SW-S3     90_05   24->25 MPa     2431 vs 2445 s              8.8%
#     SW-S3     90_06   24->25 MPa     2428 vs 2445 s              9.1%
#     SW-S4     90_07   19->20 MPa     1404 vs 1320 s (stage 2)    6.9%
#     SW-S4     90_08   19->20 MPa     1402 vs 1320 s (stage 2)    6.8%
#
# THE REPORTING-CHANNEL CORRECTION.  The scores above use differential_stress_reaction_mpa_pp,
# not differential_stress_mpa_pp.  The latter is (sigma1_pp - 30e6)*1e-6: it subtracts a TOTAL
# confining stress from a SKELETON axial stress and therefore reads alpha*p ~= 3.5 MPa low for
# the entire run.  Two independent operators agree against it -- the load-cell reaction
# (|top reaction|/A - confining) and sigma1 - sigma3_bulk -- and they agree with each other to
# < 0.4 MPa and with the digitized pre-event plateau to 0.1-0.5 MPa on SW-S4.  The broken channel
# is referenced nowhere outside [Postprocessors], so no physics was affected and no re-run was
# needed; the notebooks were repointed instead.  It is the channel the paper-frame tau and
# sigma'_n operators already consumed, so the margin analysis was never contaminated.
#
# WHAT IS LEFT, AND IT IS NOT THE ONSET.  With the corrected channel the residual differential
# stress splits cleanly by fracture type:
#
#     SW-T1 90_01   final sigma_d 71.52 vs 62.68 MPa   +8.83   UNDER-weakened   res_c = 11.176 MPa
#     SW-T2 90_03   final sigma_d 67.36 vs 62.84 MPa   +4.52   UNDER-weakened   res_c = 10.695 MPa
#     SW-S3 90_05   final sigma_d  1.60 vs  5.50 MPa   -3.90   OVER-weakened    res_c = 0
#     SW-S4 90_08   final sigma_d  5.36 vs  5.14 MPa   +0.22   correct          res_c = 0
#
# The two mated tensile fractures keep too much interlock after the burst; the saw cut that was
# given none keeps too little.  SW-S4, whose roughness-degradation floor supplies its residual,
# is already right.  So the 91-series moves residual_cohesion only, at fixed peak envelope, on
# the three specimens that need it -- and brackets D_c on SW-S4, where the remaining error is
# the SHAPE of the transition rather than its level.
#
# THIS DECK.  The conservative half of the SW-T2 residual bracket: residual_cohesion
# 1.0695e7 -> 9.71e6 Pa (-0.98 MPa), peak cohesion unchanged at 3.320e7 Pa.
#
# SW-T2 is the specimen with the least to gain -- 90_03 already scores 6.3% -- so the risk here
# is losing a good case to an over-correction.  This deck exists so that outcome is recoverable
# without another round.  Expect final sigma_d 64-66 MPa; it should be strictly between 90_03's
# 67.36 and 91_03's result, and if it is not, the residual response is nonlinear in cohesion.
#
# =============================================================================================
# ==============================================================================
# 90_03_swt2_bbfast_theta30_cohesion_c33p2_kernel_SV_biot0p6
# GENERATED 2026-08-16 by scripts/build_paper_corrected_decks.py from
#   SWT2/87_02_swt2_bbfast_injfix_kernel_SV_biot0p6.i
# -- do not hand-edit; regenerate instead. The parent is left untouched.
#
# WHY: scripts/paper_parameter_audit.py compared all four decks against Ye &
# Ghassemi (2018) itself rather than against each other, and found that several
# constants presented as measured joint properties were invented. Every value
# changed below is derived in scripts/refit_joint_constants_from_paper.py from
# the paper's own Table 1, Table 2 and Sec. 2.1. Nothing is tuned to a run.
#
# CONTROLLED AXIS: fracture angle AND strength parameterisation
#
# 1. MESH  31.000 -> 30.000 deg, as 89_03; see that deck's header.
# 2. STRENGTH  phi_r = 46.29 deg, c = 0  ->  phi_r = 29.756 deg,
#    cohesion = 31.65 MPa, residual_cohesion = 10.695 MPa, tail phi = 29.756 deg.
#    46.29 deg is essentially the paper's INTACT-rock friction angle of 46 deg,
#    which is not a joint property. The refitted cohesion is 104 % of the
#    30.30 MPa intact cohesion implied by the paper's own UCS and phi -- exactly
#    what a fully mated Mode-I fracture should show, since its asperities ARE
#    intact rock. d(tau)/d(sigma'_n) changes 0.999 -> 0.553.
#
# UNCHANGED AND DELIBERATELY SO: slip-weakening D_c, exponent and tail floor;
# dilation angles; normal-closure constants; hydraulic constants; every BC and
# the load path. The tail floor is an ABSOLUTE friction coefficient with no JRC
# or JCS in it, so refitting the peak envelope leaves its calibration valid.
#
# STATUS: CANDIDATE, not a correction. Score against 89_03 (mesh only) to separate the two effects.
# ==============================================================================
# ==============================================================================
# 87_02_swt2_bbfast_injfix_kernel_SV_biot0p6
# GENERATED 2026-08-16 from Ye2018_SWT2_BBFast_sweep_21_F0p90_Pp0p60_T40p20_U0p84_A0p0165_BBhyd_IOsafe_kernel_SV_biot0p6.i -- injection schedule rebuilt from the
# 2026-08-16 re-extracted validation curve. Only the injection_pressure function and the output
# file_base names differ from the parent deck.
# ==============================================================================
# 87_02_swt2_bbfast_injfix_kernel_SV_biot0p6
# GENERATED 2026-08-15 from Ye2018_SWT2_BBFast_sweep_21_F0p90_Pp0p60_T40p20_U0p84_A0p0165_BBhyd_IOsafe.i -- do not hand-edit; regenerate instead.
#
# Changes applied on 2026-08-15:
#   1. Storage kernel: the combined AD mass-balance kernel
#      OrcaFullySaturatedSinglePhaseMassTimeDerivativeKernel, assembling
#      (1/M)*dp/dt + alpha*div(du/dt) in one correctly-coupled object. This replaces
#      the split OrcaSinglePhaseMassTimeDerivativeKernel +
#      OrcaSinglePhaseMassVolumetricExpansionKernel pair, which drops the
#      grain-compressibility storage (alpha-phi)/K_s and uses porosity where the Biot
#      coefficient belongs.
#   2. confining_pressure set to 30e6 Pa (was 30e6).
#      NOTE: confining_pressure is a live BC magnitude here, not just a diagnostic
#      label -- it feeds the czm_pressure_x / czm_pressure_y BC function expressions.
#      A 29.4 -> 30.0 MPa change was measured on 68_02 on 2026-08-14 and moved every
#      Table-2 metric further from target. The 29.4e6 version is preserved unchanged
#      in Ye2018_SWT2_BBFast_sweep_21_F0p90_Pp0p60_T40p20_U0p84_A0p0165_BBhyd_IOsafe.i.
#   3. Output file bases repointed to this deck's own name.
#
#   4. biot_coefficient raised 1e-12 -> 0.6. The parent value is below the porosity
#      (0.001), which is unphysical: Biot's coefficient cannot be smaller than
#      porosity. At 1e-12 the bulk rock is poroelastically decoupled -- pore pressure
#      does not enter the bulk effective stress and bulk strain does not drive fluid.
#      This is a RECALIBRATION, not a normalisation: it changes the Biot modulus by
#      roughly a factor of 20 and turns on the effective-stress coupling, so the
#      existing onset timing and strength-envelope tuning will not carry over.
#
# The parent deck Ye2018_SWT2_BBFast_sweep_21_F0p90_Pp0p60_T40p20_U0p84_A0p0165_BBhyd_IOsafe.i is left untouched as the reference configuration.
# ==============================================================================
################################################################################
# I/O-SAFE RECOVERY SWEEP V4 SWT2-21: KINEMATIC APERTURE
# Parent/control: Ye2018_SWT2_BBFast_sweep_18_F0p90_Pp0p60_T40p20_U0p84_A0p0168.
# Purpose: replace v18 exponential closure with bounded Barton-Bandis; high aperture bracket.
# Corrected coupling: dilation_opens_joint=true is paired with
# use_kinematic_aperture=true; the separate cumulative-dilation feed is zero.
# The reported normal dilation uses the actual global interface jump.
# frame factor = 0.900
# peak friction offset = 0.600 deg
# post-slip tail friction angle = 40.200 deg
# normal-unload retention fraction U = 0.840000
# kinematic hydraulic aperture scale A = 0.01650000
# hydraulic normal-closure type = barton_bandis (bounded)
# I/O safety: CSV every step; Exodus only at FINAL; one checkpoint
# generation retained every 800 time steps.
################################################################################

################################################################################
# Ye and Ghassemi (2018) SW-T2: minimal timing recalibration v2
#
# Geometry: H=0.13270 m, D=0.05052 m,
# fracture angle=31.0 deg, mesh=mesh/ye2018_sw_T2_mesh_size_5.e
# Paper properties: E=67 GPa, nu=0.32, UCS/JCS=150 MPa, JRC=14.63
# Protocol: sigma3=30 MPa, Po=5 MPa, Pi=8..28..8 MPa.
#
# MINIMAL TIMING RECALIBRATION AFTER REJECTING BACK-ANALYSIS V1:
#   - retain the stable transfer-deck load train, preload, weakening,
#     dilation, residual roughness, strength floor, and time stepping;
#   - replace only the pressure schedule/end time with the digitized
#     Figure-7 protocol and report boundary-average pressures;
#   - for SW-T1 only, apply the bounded +0.593 degree peak-threshold
#     correction that moves initiation from ~25.5 to ~27.9 MPa;
#   - do not reuse the v1 soft load train, cubic weakening, tail-angle
#     reduction, shear-strength floor, or opening-output suppression.
# This remains a candidate until its distinct CSV completes.
# Table-2 anchors:
#   basic friction angle       = 45.6918 deg (24 MPa pre-slip hold)
#   weakened friction angle    = 43.1056 deg (28 MPa post-slip hold)
#   dilation angle             = 13.9654 deg (peak |dn|/ds)
#   hydraulic dilation scale   = 0.019789
#   retained aperture fraction = 0.747331
#   Eq.-9 flow W/L             = 0.813243
#
# REQUIRED PRE-FULL-RUN GATE:
#   (1) t=55 s plastic slip must be zero;
#   (2) first 8 MPa hold should give q~169.591 MPa and
#       tau~74.87 MPa;
#   (3) axial_pres_final is calibrated on this size-5 mesh; recheck this gate
#       whenever the mesh, penalty, elastic properties, or boundary setup changes.
################################################################################

mesh_file = mesh/kalantar2025_og_sh_theta29_size3.e   # KALANTAR: OG-SH factor-3 mesh, verified 5b9fcc5
sample_radius = 0.02499   # KALANTAR: Table 1, D = 49.98 mm
sample_area = 1.961924926e-03   # KALANTAR: pi r^2
bulk_sin_theta = 0.4848096202463371   # KALANTAR: sin(29.0 deg)
bulk_cos_theta = 0.8746197071393957   # KALANTAR: cos(29.0 deg)
axial_bc_penalty = 1.3282e+12   # KALANTAR: MEASURED K_sys 796 kN/mm / A -- Ye2018 had to infer this

axial_pres_initial = -2.484637e-05   # KALANTAR: -sigma_3/penalty, t=0 equilibrium
axial_pres_final = -1.767907e-04   # KALANTAR: GATED series-spring: sigma_1/penalty + C_ax*(sigma_1-sigma_3), sigma_1 = 94.65 MPa, C_ax = 1.7118e-12 m/Pa

youngs_modulus = 6.3e+10   # KALANTAR: section 2.1
poissons_ratio = 0.16   # KALANTAR: section 2.1
strain_model = incremental
initial_stress = '-3.3e+07 -3.3e+07 -3.3e+07'   # KALANTAR: sigma_3 = 33 MPa recovered from Table 2, NOT the 30 MPa in the prose
biot_coefficient = 0.6

initial_porosity = 0.0033   # KALANTAR: section 2.1, ~0.33 %
matrix_permeability = 1.4e-20   # KALANTAR: section 2.1

confining_pressure = 3.3e+07   # KALANTAR: section 2.3 + Table 2 recovery

production_pressure = 3e+06   # KALANTAR: section 2.3, constant throughout
fault_pressure_coefficient = 1.0   # KALANTAR: NEUTRALISED. The parent's value was fitted to Ye2018; do not import it

penalty_tangent = 1e13
initial_roughness = 1.0
residual_roughness = 0.10

tangential_traction_tolerance = 1e-16

initial_hydraulic_aperture = 4.8700e-06   # KALANTAR: Table 2 stage 1 a_h = 4.87 um, anchored at the stage-1 sigma'_n below

aperture_scale = 0.0165
normal_stress_aperture_compliance = 0.0
reference_effective_normal_stress = 4.2990e+07   # KALANTAR: Table 2 stage 1 sigma'_n = 42.99 MPa -- the stress at which initial_hydraulic_aperture holds, so the closure term vanishes there

use_nonlinear_normal_closure = true
nonlinear_closure_type = barton_bandis
bb_max_aperture_closure = 1.2e-6

bb_initial_normal_stiffness = 1.25e13
bb_stress_exponent = 4.0
dilation_scale = 0.0

retention_residual = 0.747330960854

self_propping_scale = 0.0
self_propping_exponent = 1.0
use_slip_damage = true   # KALANTAR: gouge fill is the only term in the aperture law that SUBTRACTS
slip_damage_scale = 1.1500e-06   # KALANTAR: Table 2's irreversible a_h loss, 1.15 um (sigma'_n FALLS over the same stages, so a reversible law has the wrong sign)

slip_damage_onset_slip = 0.0   # KALANTAR: Table 2 loses aperture from stage 1->2, so gouge accrues from first slip

slip_damage_characteristic_slip = 1.50e-05   # KALANTAR: slip over which the gouge term saturates
min_hydraulic_aperture = 7.4400e-07   # KALANTAR: 0.2x Table 2's minimum (3.72 um) -- the round-1 floor was an inherited Ye2018 value that clipped the answer

max_hydraulic_aperture = 1.4610e-05   # KALANTAR: 3x Table 2's maximum (4.87 um)

compute_transmissibility = true

fault_thickness = 1e-3

fluid_density_ref = 1000
fluid_viscosity_ref = 1.0e-3   # KALANTAR: stated under eq (7)
fluid_bulk_modulus = 2.2e9  # water at 20 C (Sec. 2.5); was 4.7835616438e9, 2.17x too stiff
paper_flow_width_over_length_og_sh = 0.606072   # KALANTAR: W/L, W = 49.98 mm, L = 82.4654 mm (paper frame). Eq (7) as printed is 10.3x out -- see audit section 8
mesh_flow_width_over_length_og_sh = 0.606012   # KALANTAR: W/L, W = 49.98 mm, L = 82.4736 mm (mesh frame). Eq (7) as printed is 10.3x out -- see audit section 8
ml_per_m3_per_min = 6.0e7

exodus_file_base = results_exodus_hpc/110_21_og_sh_swexp1p20_r8_hpc   # ROUND 8: self-named output
csv_file_base = results_csv_hpc/110_21_og_sh_swexp1p20_r8_hpc   # ROUND 8: self-named output
checkpoint_file_base = results_checkpoint_hpc/110_21_og_sh_swexp1p20_r8_hpc   # ROUND 8: self-named output

[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

[Problem]
  boundary_restricted_elem_integrity_check = false  # split-interface lower-D map is orientation-sensitive
  kernel_coverage_check = false  # block 900 (fracture_surface) is output-only
  extra_tag_vectors = 'mech_reaction mass_reaction'
[]

[Mesh]

  [file_mesh]
    type = FileMeshGenerator
    file = ${mesh_file}
  []

  [sidesets_from_nodesets]
    type = SideSetsFromNodeSetsGenerator
    input = file_mesh
    nodesets_to_convert = 'top_nodeset bottom_nodeset sides_nodeset'
  []
  [source_in]
    type = ExtraNodesetGenerator
    input = sidesets_from_nodesets
    coord = '-0.019992000 0.0 0.023933478'   # exact interface node on the 30 deg plane
    new_boundary = source_in
    use_closest_node = true
  []
  [source_out]
    type = ExtraNodesetGenerator
    input = source_in
    coord = '0.019992000 0.0 0.096066522'   # exact interface node on the 30 deg plane
    new_boundary = source_out
    use_closest_node = true
  []
  [fault_split_3d]
    type = OrcaFaultInterface3DGenerator
    input = source_out
    nodesets = 'fracture_interface'
    preserve_front_nodes = true
    split_only_interior_nodes = true
    rebuild_sidesets_from_nodesets = false
    add_interface_on_two_sides = true
    secondary_sidesets = 'fracture_interface_other_side'
  []
  construct_side_list_from_node_list = false

  # Explicit 2-D output block coincident with the solved CZM interface. Required by
  # every AuxVariable carrying block = fracture_surface.
  [fracture_surface_output]
    type = LowerDBlockFromSidesetGenerator
    input = fault_split_3d
    sidesets = fracture_interface
    new_block_id = 900
    new_block_name = fracture_surface
  []
[]

[Variables]
  # Restricted to the 3-D bulk: the mesh also carries the lower-dimensional
  # 'fracture_surface' block (id 900) used only for interface output.
  [disp_x]
    block = 'top_block bottom_block'
  []
  [disp_y]
    block = 'top_block bottom_block'
  []
  [disp_z]
    block = 'top_block bottom_block'
  []
  [pore_pressure]
    block = 'top_block bottom_block'
  []
[]

[ICs]
  [pp_ic]
    type = ConstantIC
    variable = pore_pressure
    value = 5e6
  []
[]

[Functions]

  [axial_disp_ramp]
      type = ParsedFunction

      expression = 'if(t<2.0,${axial_pres_initial},if(t<55.0,${axial_pres_initial}+(${axial_pres_final}-${axial_pres_initial})*(t-2.0)/53.0,${axial_pres_final}))'
    []

  [injection_pressure]
    # REBUILT 2026-08-16 from SWT2_injection_pressure_MPA.csv (re-extraction dated 2026-08-16).
    # The previous schedule was a hand-built idealised staircase: correct hold LEVELS but
    # transition times late by +48..+155 s, and the 28 MPa peak hold only 220 s of measured
    # duration. Because injection pressure is the DRIVER, that timing error propagates into
    # flow rate, permeability, slip onset and the unload branch -- so it must be fixed before
    # any friction/dilation parameter is re-tuned against these curves.
    #
    # Plateau VALUES are snapped to the nominal 5/8/12/16/20/24/28 MPa the experiment held;
    # only the measured TRANSITION TIMES are adopted. Feeding the raw digitised trace would
    # inject +-0.3 MPa extraction jitter as a real pressure BC and excite spurious transients.
    #   whole-record RMSE against the measurement: 1.536 MPa -> 0.266 MPa
    type = PiecewiseLinear
    x = '0.0 100.0 400.0 500.0 800.0 900.0 1200.0 1300.0 1600.0 1700.0 2000.0 2100.0 2400.0 2500.0 2800.0 2900.0 3200.0 3300.0 3600.0'
    y = '3000000.0 6000000.0 6000000.0 9000000.0 9000000.0 12000000.0 12000000.0 15000000.0 15000000.0 18000000.0 18000000.0 15000000.0 15000000.0 12000000.0 12000000.0 9000000.0 9000000.0 6000000.0 6000000.0'
  []

  [production_pressure_fn]
    type = ConstantFunction
    value = ${production_pressure}
  []

  [sigma3_x]
    type = ParsedFunction
    expression = '-${confining_pressure}*x/${sample_radius}'
  []
  [sigma3_y]
    type = ParsedFunction
    expression = '-${confining_pressure}*y/${sample_radius}'
  []
[]

[Kernels]
  [mech_x]
    type = OrcaPoroMechKernel
    variable = disp_x
    pore_pressure = pore_pressure
    component = 0
  []
  [mech_y]
    type = OrcaPoroMechKernel
    variable = disp_y
    pore_pressure = pore_pressure
    component = 1
  []
  [mech_z]
    type = OrcaPoroMechKernel
    variable = disp_z
    pore_pressure = pore_pressure
    component = 2
    extra_vector_tags = 'mech_reaction'
  []

#   [fluid_storage]
#     type = OrcaSinglePhaseMassTimeDerivativeKernel
#     variable = pore_pressure
#     multiply_by_fluid_density = true
#     save_in = inj_flux_aux
#   []
  [darcy]
    type = OrcaFullySaturatedSinglePhaseDarcySUPGKernel
    variable = pore_pressure
    multiply_by_fluid_density = true
    use_supg = true
    save_in = inj_flux_aux
    extra_vector_tags = mass_reaction
  []
#   [mass_vol_expansion]
#     type = OrcaSinglePhaseMassVolumetricExpansionKernel
#     variable = pore_pressure
#     multiply_by_fluid_density = true
#   []
  # (1/M)*dp/dt + alpha*div(du/dt)  [volume form] -- KERNEL FIX 2026-08-14: combined,
  # correctly-coupled mass time-derivative kernel, replacing the old split
  # fluid_storage + mass_vol_expansion pair above (commented out, kept for reference).
  # Validated against 68_02_sw4_bbfast_tail6p75_eta3p25_m0 (this exact deck) in
  # SW4_July10/SW4_68_TARGETED_RESIDUAL_SWEEPS/ -- see CHANGELOG/memory
  # sw-s4-kernel-alpha-backanalysis-2026-08-14 for the full back-analysis.
  [fluid_storage]
    type                 = OrcaFullySaturatedSinglePhaseMassTimeDerivativeKernel
    variable             = pore_pressure
    coupling_type        = HydroMechanical
    multiply_by_fluid_density = true
    extra_vector_tags = mass_reaction
  []
[]

[InterfaceKernels]
  [czm_mech_x]
    type = OrcaMechInterfaceKernel
    boundary = fracture_interface
    variable = disp_x
    neighbor_var = disp_x
    component = 0
  []
  [czm_mech_y]
    type = OrcaMechInterfaceKernel
    boundary = fracture_interface
    variable = disp_y
    neighbor_var = disp_y
    component = 1
  []
  [czm_mech_z]
    type = OrcaMechInterfaceKernel
    boundary = fracture_interface
    variable = disp_z
    neighbor_var = disp_z
    component = 2
    extra_vector_tags = 'mech_reaction'
  []

  [fault_pressure_x]
    type = OrcaCZMFluidPressureInterfaceKernel
    boundary = fracture_interface
    variable = disp_x
    neighbor_var = disp_x
    component = 0
    displacements = 'disp_x disp_y disp_z'
    pressure_traction_coefficient = -${fault_pressure_coefficient}
  []
  [fault_pressure_y]
    type = OrcaCZMFluidPressureInterfaceKernel
    boundary = fracture_interface
    variable = disp_y
    neighbor_var = disp_y
    component = 1
    displacements = 'disp_x disp_y disp_z'
    pressure_traction_coefficient = -${fault_pressure_coefficient}
  []
  [fault_pressure_z]
    type = OrcaCZMFluidPressureInterfaceKernel
    boundary = fracture_interface
    variable = disp_z
    neighbor_var = disp_z
    component = 2
    displacements = 'disp_x disp_y disp_z'
    pressure_traction_coefficient = -${fault_pressure_coefficient}
    extra_vector_tags = 'mech_reaction'
  []
  [czm_flow]
    type = OrcaFractureFlowInterfaceKernel
    boundary = fracture_interface
    variable = pore_pressure
    neighbor_var = pore_pressure
    pressure_penalty_length = 5e-4
    multiply_by_fluid_density = true
    save_in = 'inj_flux_aux inj_flux_aux'
    save_in_var_side = 'm s'
    extra_vector_tags = mass_reaction
  []
[]

[BCs]
  [confine_x]
    type = FunctionNeumannBC
    variable = disp_x
    boundary = sides_nodeset
    function = sigma3_x
  []
  [confine_y]
    type = FunctionNeumannBC
    variable = disp_y
    boundary = sides_nodeset
    function = sigma3_y
  []
  [base_fixed_z]
    type = DirichletBC
    variable = disp_z
    boundary = bottom_nodeset
    value = 0
  []
  [axial_load]

    type = FunctionPenaltyDirichletBC
    variable = disp_z
    boundary = top_nodeset
    function = axial_disp_ramp
    penalty = ${axial_bc_penalty}
  []
  [pin_x]
    type = DirichletBC
    variable = disp_x
    boundary = no_disp_x
    value = 0
  []
  [pin_y]
    type = DirichletBC
    variable = disp_y
    boundary = no_disp_y
    value = 0
  []
  [injection]
    type = FunctionDirichletBC
    variable = pore_pressure
    boundary = source_in
    function = injection_pressure
  []
  [production]
    type = DirichletBC
    variable = pore_pressure
    boundary = source_out
    value = ${production_pressure}
  []
[]

[AuxVariables]
  [inj_flux_aux]
    block = 'top_block bottom_block'
  []
  [react_disp_z]
    order = FIRST
    family = LAGRANGE
    block = 'top_block bottom_block'
  []
  [react_pore_pressure]
    order = FIRST
    family = LAGRANGE
    block = 'top_block bottom_block'
  []
  [stress_xx]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [stress_yy]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [stress_zz]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [stress_xy]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [stress_xz]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [stress_yz]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [darcy_vel_x]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [darcy_vel_y]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [darcy_vel_z]
    order = CONSTANT
    family = MONOMIAL
    block = 'top_block bottom_block'
  []
  [traction_x]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [traction_y]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [traction_z]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [normal_traction]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [tangent_traction]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [jump_x]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [jump_y]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [jump_z]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [normal_jump]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [tangent_jump]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [aperture_mech]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [aperture_mech_raw]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [aperture_open]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [aperture_hydraulic]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [fracture_permeability]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [cumulative_dilation]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [fracture_state]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [roughness_state]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [roughness_damage]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [roughness_retention_factor]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [self_propping_aperture]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [limit_tau]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [plastic_slip_increment]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [dilation_jump_increment]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [cumulative_plastic_slip]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [friction_coefficient_effective]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [cohesion_effective]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [fracture_darcy_vel_x]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [fracture_darcy_vel_y]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
  [fracture_darcy_vel_z]
    order = CONSTANT
    family = MONOMIAL
    block = fracture_surface
  []
[]

[AuxKernels]
  [react_disp_z_aux]
    type = TagVectorAux
    vector_tag = mech_reaction
    v = disp_z
    variable = react_disp_z
    remove_variable_scaling = true
    block = 'top_block bottom_block'
  []
  [react_pore_pressure_aux]
    type = TagVectorAux
    vector_tag = mass_reaction
    v = pore_pressure
    variable = react_pore_pressure
    remove_variable_scaling = true
    block = 'top_block bottom_block'
  []
  [stress_xx_aux]
    type = ADMaterialRankTwoTensorAux
    variable = stress_xx
    property = stress
    i = 0
    j = 0
    block = 'top_block bottom_block'
  []
  [stress_yy_aux]
    type = ADMaterialRankTwoTensorAux
    variable = stress_yy
    property = stress
    i = 1
    j = 1
    block = 'top_block bottom_block'
  []
  [stress_zz_aux]
    type = ADMaterialRankTwoTensorAux
    variable = stress_zz
    property = stress
    i = 2
    j = 2
    block = 'top_block bottom_block'
  []
  [stress_xy_aux]
    type = ADMaterialRankTwoTensorAux
    variable = stress_xy
    property = stress
    i = 0
    j = 1
    block = 'top_block bottom_block'
  []
  [stress_xz_aux]
    type = ADMaterialRankTwoTensorAux
    variable = stress_xz
    property = stress
    i = 0
    j = 2
    block = 'top_block bottom_block'
  []
  [stress_yz_aux]
    type = ADMaterialRankTwoTensorAux
    variable = stress_yz
    property = stress
    i = 1
    j = 2
    block = 'top_block bottom_block'
  []
  [darcy_x_aux]
    type = OrcaDarcyVelocityComponent
    component = 0
    variable = darcy_vel_x
    fluid_pressure = pore_pressure
    block = 'top_block bottom_block'
  []
  [darcy_y_aux]
    type = OrcaDarcyVelocityComponent
    component = 1
    variable = darcy_vel_y
    fluid_pressure = pore_pressure
    block = 'top_block bottom_block'
  []
  [darcy_z_aux]
    type = OrcaDarcyVelocityComponent
    component = 2
    variable = darcy_vel_z
    fluid_pressure = pore_pressure
    block = 'top_block bottom_block'
  []
  [traction_x_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = traction_x
    variable = traction_x
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [traction_y_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = traction_y
    variable = traction_y
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [traction_z_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = traction_z
    variable = traction_z
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [normal_traction_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = normal_traction
    variable = normal_traction
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [tangent_traction_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = tangent_traction
    variable = tangent_traction
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [jump_x_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = jump_x
    variable = jump_x
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [jump_y_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = jump_y
    variable = jump_y
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [jump_z_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = jump_z
    variable = jump_z
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [normal_jump_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = normal_jump
    variable = normal_jump
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [tangent_jump_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = tangent_jump
    variable = tangent_jump
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [aperture_mech_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = mechanical_aperture
    variable = aperture_mech
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [aperture_mech_raw_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = mechanical_aperture_raw
    variable = aperture_mech_raw
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [aperture_open_aux]
    type = ParsedAux
    check_boundary_restricted = false
    variable = aperture_open
    boundary = fracture_interface
    coupled_variables = normal_jump
    expression = 'if(normal_jump > 0.0, normal_jump, 0.0)'
    execute_on = TIMESTEP_END
  []
  [aperture_hydraulic_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = hydraulic_aperture
    variable = aperture_hydraulic
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [fracture_permeability_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = fracture_permeability
    variable = fracture_permeability
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [cumulative_dilation_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = cumulative_dilation
    variable = cumulative_dilation
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [fracture_state_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = fracture_state
    variable = fracture_state
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [roughness_state_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = roughness_state
    variable = roughness_state
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [roughness_damage_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = roughness_damage
    variable = roughness_damage
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [roughness_retention_factor_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = roughness_retention_factor
    variable = roughness_retention_factor
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [self_propping_aperture_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = self_propping_aperture
    variable = self_propping_aperture
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [limit_tau_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = limit_tau
    variable = limit_tau
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [plastic_slip_increment_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = plastic_slip_increment
    variable = plastic_slip_increment
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [dilation_jump_increment_aux]
    type = ADMaterialRealAux
    check_boundary_restricted = false
    property = dilation_jump_increment
    variable = dilation_jump_increment
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [cumulative_plastic_slip_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = cumulative_plastic_slip
    variable = cumulative_plastic_slip
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [friction_coefficient_effective_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = friction_coefficient_effective
    variable = friction_coefficient_effective
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [cohesion_effective_aux]
    type = MaterialRealAux
    check_boundary_restricted = false
    property = cohesion_effective
    variable = cohesion_effective
    boundary = fracture_interface
    execute_on = TIMESTEP_END
  []
  [fracture_darcy_x_aux]
    type = OrcaFractureDarcyVelocityComponent
    component = 0
    variable = fracture_darcy_vel_x
    fluid_pressure = pore_pressure
    boundary = fracture_interface
    check_boundary_restricted = false
    execute_on = TIMESTEP_END
  []
  [fracture_darcy_y_aux]
    type = OrcaFractureDarcyVelocityComponent
    component = 1
    variable = fracture_darcy_vel_y
    fluid_pressure = pore_pressure
    boundary = fracture_interface
    check_boundary_restricted = false
    execute_on = TIMESTEP_END
  []
  [fracture_darcy_z_aux]
    type = OrcaFractureDarcyVelocityComponent
    component = 2
    variable = fracture_darcy_vel_z
    fluid_pressure = pore_pressure
    boundary = fracture_interface
    check_boundary_restricted = false
    execute_on = TIMESTEP_END
  []
[]

[Materials]
  [mech]
    type = OrcaMechMaterial
    youngs_modulus = ${youngs_modulus}
    poissons_ratio = ${poissons_ratio}
    strain_model = ${strain_model}
    initial_stress = ${initial_stress}
    block = 'top_block bottom_block'
  []
  [rockHM]
    type = OrcaTHMaterial
    pore_pressure = pore_pressure
    initial_porosity = ${initial_porosity}
    initial_permeability = '${matrix_permeability} 0 0  0 ${matrix_permeability} 0  0 0 ${matrix_permeability}'
    fluid_properties_model = user
    fluid_density_model = constant
    fluid_density_ref = ${fluid_density_ref}
    fluid_bulk_modulus = ${fluid_bulk_modulus}
    fluid_viscosity_ref = ${fluid_viscosity_ref}
    biot_modulus_model = constant
    fluid_thermal_expansion_model = user
    block = 'top_block bottom_block'
  []
  [biot]
    type = OrcaBiotCoefficientMaterial
    model = user
    biot_coefficient = ${biot_coefficient}
  []
  [gravity]
    type = OrcaGravityVectorMaterial
    gravity = '0 0 0'
  []

  [czm_jump]
    type = OrcaCZMComputeDisplacementJump
    boundary = fracture_interface
  []
  [czm_pressure]
    type = OrcaCZMInterfacePressure
    boundary = fracture_interface
    pore_pressure = pore_pressure
  []
  [czm_contact]

    type = OrcaBartonBandisContactTractionFastADHardening
    boundary = fracture_interface

    use_hyperbolic_normal_closure = true
    initial_normal_stiffness = 2.443e11
    maximum_closure = 4.591e-5
    normal_closure_stress_exponent = 3.28
    normal_closure_offset = 4.433e-5
    normal_unload_retention_fraction = 0.84
    normal_unload_retention_time = 0.0
    normal_reclosure_stiffness_multiplier = 1.0
    normal_unload_activation_slip = 5.0e-5
    reported_reversible_normal_opening_scale = 1.0
    reported_reversible_normal_opening_retention_fraction = 0.0
    reported_reversible_normal_opening_retention_activation_slip = 50e-6
    penalty_tangent = ${penalty_tangent}
    normal_traction_tolerance = 0.0
    tangential_traction_tolerance = ${tangential_traction_tolerance}

    jrc = 15.60   
    jcs = 1.53e+08   
    residual_friction_angle_degrees = 21.519   # granite basic friction, measured on this campaign's own saw cut (SW-S3). Was 46.29182452, above every measured granite value.
    use_scale_correction = false
    use_mobilized_jrc = false
    compressive_normal_stress_floor = 1e3
    pore_pressure_strength_coefficient = 0.0
    use_slip_weakening = true
    characteristic_slip_distance = 1.000e-04   
    slip_weakening_exponent = 1.20   # ROUND 8: faster early-weakening arm
    slip_weakening_residual_friction_angle_degrees = 25.930   # slip destroys ROUGHNESS, not the rock's basic friction angle -- Barton's own picture. Was 40.2.
    cohesion = 1.2e+06   # asperity interlock of a MATED Mode-I fracture; pins the peak envelope through Table 2's last stick stage.
    residual_cohesion = 0.0   # interlock surviving the burst; pins the post-burst stage. Table 2 shows this joint retaining most of its dilation, so it does not lose all interlock in one event.  # 91_04: half the 91_03 cut. Was 1.0695e7.
    use_dilatancy = true
    use_decoupled_dilation = true
    dilation_angle_peak_degrees = 4.300   
    dilation_angle_residual_degrees = 4.300   
    dilation_decay_distance = 1.5e-4
    dilation_opens_joint = true
    accumulate_irreversible_dilation = true
    cap_dilation_to_available_closure = false
    max_dilation_increment = 0.0

    use_roughness_degradation = true
    roughness_state_initial = ${initial_roughness}
    roughness_state_residual = ${residual_roughness}
    roughness_characteristic_slip = 1.5e-4

    max_plastic_slip_increment = 0.0
    tangential_viscosity = 400000000000
    min_tau_limit = 0.0
    max_return_mapping_iterations = 100
    relative_tolerance = 1e-10
  []
  [czm_global_traction]
    type = OrcaComputeGlobalTractionSmallStrain
    boundary = fracture_interface
  []

  [aperture_mech]
    type = ADOrcaCZMComputeMechanicalAperture
    boundary = fracture_interface
    jump_property_name = interface_displacement_jump
    aperture_property_name = mechanical_aperture
    raw_aperture_property_name = mechanical_aperture_raw
    clamp_to_zero = true
  []
  [czm_sigma_n]
    type = OrcaCZMRealVectorCartesianComponent
    boundary = fracture_interface
    real_vector_value = interface_traction
    property_name = czm_sigma_n
    index = 0
  []
  [czm_aperture]
    type = ADOrcaRoughnessDamageFracturePermeability
    boundary = fracture_interface
    mechanical_aperture_name = mechanical_aperture
    dilation_jump_increment_name = dilation_jump_increment
    roughness_name = roughness_state
    hydraulic_aperture_name = hydraulic_aperture
    fracture_permeability_name = fracture_permeability
    cumulative_dilation_name = cumulative_dilation
    roughness_retention_factor_name = roughness_retention_factor
    self_propping_aperture_name = self_propping_aperture
    normal_stress_aperture_name = normal_stress_aperture
    effective_normal_compression_name = effective_normal_compression
    effective_normal_traction_name = czm_sigma_n
    transmissibility_name = fracture_transmissivity

    use_kinematic_aperture = true
    initial_hydraulic_aperture = ${initial_hydraulic_aperture}
    aperture_scale = ${aperture_scale}
    normal_stress_aperture_compliance = ${normal_stress_aperture_compliance}
    reference_effective_normal_stress = ${reference_effective_normal_stress}
    use_nonlinear_normal_closure = ${use_nonlinear_normal_closure}
    nonlinear_closure_type = ${nonlinear_closure_type}
    bb_max_aperture_closure = ${bb_max_aperture_closure}
    bb_initial_normal_stiffness = ${bb_initial_normal_stiffness}
    bb_stress_exponent = ${bb_stress_exponent}
    dilation_scale = ${dilation_scale}
    retention_residual = ${retention_residual}
    self_propping_scale = ${self_propping_scale}
    self_propping_exponent = ${self_propping_exponent}
    use_slip_damage = ${use_slip_damage}
    slip_damage_scale = ${slip_damage_scale}
    slip_damage_characteristic_slip = ${slip_damage_characteristic_slip}
    slip_damage_onset_slip = ${slip_damage_onset_slip}
    cumulative_plastic_slip_name = cumulative_plastic_slip
    cumulative_plastic_slip_is_ad = false
    slip_damage_aperture_name = slip_damage_aperture

    min_hydraulic_aperture = ${min_hydraulic_aperture}
    max_hydraulic_aperture = ${max_hydraulic_aperture}
    compute_transmissibility = ${compute_transmissibility}
    fluid_viscosity = ${fluid_viscosity_ref}
    fault_thickness = ${fault_thickness}
  []

  [czm_tau_1]
    type = OrcaCZMRealVectorCartesianComponent
    boundary = fracture_interface
    real_vector_value = interface_traction
    property_name = czm_tau_1
    index = 1
  []
  [czm_tau_2]
    type = OrcaCZMRealVectorCartesianComponent
    boundary = fracture_interface
    real_vector_value = interface_traction
    property_name = czm_tau_2
    index = 2
  []
  [czm_dn]
    type = OrcaCZMRealVectorCartesianComponent
    boundary = fracture_interface
    real_vector_value = interface_displacement_jump
    property_name = czm_dn
    index = 0
  []
  [czm_ds_1]
    type = OrcaCZMRealVectorCartesianComponent
    boundary = fracture_interface
    real_vector_value = interface_displacement_jump
    property_name = czm_ds_1
    index = 1
  []
  [czm_ds_2]
    type = OrcaCZMRealVectorCartesianComponent
    boundary = fracture_interface
    real_vector_value = interface_displacement_jump
    property_name = czm_ds_2
    index = 2
  []

  [czm_dn_global]
    type = OrcaCZMRealVectorScalar
    boundary = fracture_interface
    real_vector_value = displacement_jump_global
    direction = Normal
    property_name = czm_dn_global
  []

  # ---- CZM interface output properties consumed by the fracture_surface AuxKernels ----
  [fracture_surface_output_material]
    type = GenericConstantMaterial
    prop_names = fracture_surface_output_marker
    prop_values = 1
    block = fracture_surface
  []
  [traction_x_output_property]
    type = OrcaCZMRealVectorCartesianComponent
    real_vector_value = traction_global
    index = 0
    property_name = traction_x
    boundary = fracture_interface
  []
  [traction_y_output_property]
    type = OrcaCZMRealVectorCartesianComponent
    real_vector_value = traction_global
    index = 1
    property_name = traction_y
    boundary = fracture_interface
  []
  [traction_z_output_property]
    type = OrcaCZMRealVectorCartesianComponent
    real_vector_value = traction_global
    index = 2
    property_name = traction_z
    boundary = fracture_interface
  []
  [jump_x_output_property]
    type = OrcaCZMRealVectorCartesianComponent
    real_vector_value = displacement_jump_global
    index = 0
    property_name = jump_x
    boundary = fracture_interface
  []
  [jump_y_output_property]
    type = OrcaCZMRealVectorCartesianComponent
    real_vector_value = displacement_jump_global
    index = 1
    property_name = jump_y
    boundary = fracture_interface
  []
  [jump_z_output_property]
    type = OrcaCZMRealVectorCartesianComponent
    real_vector_value = displacement_jump_global
    index = 2
    property_name = jump_z
    boundary = fracture_interface
  []
  [normal_traction_output_property]
    type = OrcaCZMRealVectorScalar
    real_vector_value = traction_global
    direction = Normal
    property_name = normal_traction
    boundary = fracture_interface
  []
  [tangent_traction_output_property]
    type = OrcaCZMRealVectorScalar
    real_vector_value = traction_global
    direction = Tangent
    property_name = tangent_traction
    boundary = fracture_interface
  []
  [normal_jump_output_property]
    type = OrcaCZMRealVectorScalar
    real_vector_value = displacement_jump_global
    direction = Normal
    property_name = normal_jump
    boundary = fracture_interface
  []
  [tangent_jump_output_property]
    type = OrcaCZMRealVectorScalar
    real_vector_value = displacement_jump_global
    direction = Tangent
    property_name = tangent_jump
    boundary = fracture_interface
  []
[]

[Postprocessors]

  [fracture_interface_area_pp]
    type = AreaPostprocessor
    boundary = fracture_interface
  []
  [injection_pressure_pp]
    type = AverageNodalVariableValue
    variable = pore_pressure
    boundary = source_in
  []
  # --- FLOW-MEASUREMENT FIX 2026-08-24 (task #123) -------------------------
  # These two summed `inj_flux_aux`, the save_in quantity.  The 2026-08-06
  # back-analysis established that save_in does not reproduce the nodal
  # reaction here (mass_vol_expansion carries the mass_reaction tag but had no
  # save_in, and the two-sided sum across the split injection node does not
  # recover it either), and that the deck already builds the right quantity:
  # `react_pore_pressure`, a TagVectorAux on mass_reaction with
  # remove_variable_scaling = true.  That repoint was never carried into the
  # 93/94-series finals, so every flux number they report is ~2 orders of
  # magnitude low and the manuscript quoted values no finished run produces.
  #
  # OUTPUT-ONLY: `inj_flux_aux` is written by save_in and read by nothing but
  # these postprocessors, so the residual, the solve and every other reported
  # channel are unchanged from the runs already scored.  Only the flux
  # diagnostics move.
  [inj_reaction_sum_pp]
    type = NodalSum
    variable = react_pore_pressure
    boundary = source_in
  []
  [prod_reaction_sum_pp]
    type = NodalSum
    variable = react_pore_pressure
    boundary = source_out
  []
  # Superseded save_in sums, retained so the pre-fix numbers stay auditable and
  # the size of the correction is recoverable from a single run.
  [inj_saveiin_sum_legacy_pp]
    type = NodalSum
    variable = inj_flux_aux
    boundary = source_in
  []
  [prod_saveiin_sum_legacy_pp]
    type = NodalSum
    variable = inj_flux_aux
    boundary = source_out
  []
  # ------------------------------------------------------------------------
  [flow_rate_pp]
    type = ParsedPostprocessor
    pp_names = inj_reaction_sum_pp
    expression = 'abs(inj_reaction_sum_pp)'
  []

  [pp_outlet_pp]
    type = AverageNodalVariableValue
    variable = pore_pressure
    boundary = source_out
  []
  [pp_drop_pp]
    type = ParsedPostprocessor
    pp_names = 'injection_pressure_pp pp_outlet_pp'
    expression = 'injection_pressure_pp - pp_outlet_pp'
  []
  [flow_rate_validation_ml_min_pp]
    type = ParsedPostprocessor
    pp_names = 'hydraulic_aperture_pp pp_drop_pp'
    expression = '(${paper_flow_width_over_length_og_sh} / (12.0 * ${fluid_viscosity_ref})) * hydraulic_aperture_pp^3 * pp_drop_pp * ${ml_per_m3_per_min}'
  []
  [flow_rate_mesh_geometry_ml_min_pp]
    type = ParsedPostprocessor
    pp_names = 'hydraulic_aperture_pp pp_drop_pp'
    expression = '(${mesh_flow_width_over_length_og_sh} / (12.0 * ${fluid_viscosity_ref})) * hydraulic_aperture_pp^3 * pp_drop_pp * ${ml_per_m3_per_min}'
  []
  [flow_rate_reference_area_ml_min_pp]
    type = ParsedPostprocessor
    pp_names = 'fracture_permeability_pp pp_drop_pp'
    expression = 'fracture_permeability_pp * (7.8e-6 / (${fluid_viscosity_ref} * 7.94e-2)) * pp_drop_pp * ${ml_per_m3_per_min}'
  []
  [flow_rate_residual_volume_ml_min_pp]
    type = ParsedPostprocessor
    pp_names = flow_rate_pp
    expression = 'flow_rate_pp / ${fluid_density_ref} * ${ml_per_m3_per_min}'
  []
  [flow_rate_outlet_residual_volume_ml_min_pp]
    type = ParsedPostprocessor
    pp_names = prod_reaction_sum_pp
    expression = 'abs(prod_reaction_sum_pp) / ${fluid_density_ref} * ${ml_per_m3_per_min}'
  []
  [flow_mass_imbalance_fraction_pp]
    type = ParsedPostprocessor
    pp_names = 'inj_reaction_sum_pp prod_reaction_sum_pp'
    expression = 'abs(inj_reaction_sum_pp + prod_reaction_sum_pp) / max(abs(inj_reaction_sum_pp), 1e-30)'
  []

  [top_boundary_area_pp]
    type = AreaPostprocessor
    boundary = top_nodeset
  []
  [top_reaction_z_raw]
    type = NodalSum
    variable = react_disp_z
    boundary = top_nodeset
  []
  [top_reaction_z_abs]
    type = ParsedPostprocessor
    pp_names = top_reaction_z_raw
    expression = 'abs(top_reaction_z_raw)'
  []
  [sigma1_reaction_mpa_pp]
    type = ParsedPostprocessor
    pp_names = top_reaction_z_abs
    expression = 'top_reaction_z_abs / ${sample_area} * 1e-6'
  []
  [differential_stress_reaction_mpa_pp]
    type = ParsedPostprocessor
    pp_names = sigma1_reaction_mpa_pp
    expression = 'sigma1_reaction_mpa_pp - 33.0'
  []

  [stress_zz_top_pp]
    type = SideAverageValue
    variable = stress_zz
    boundary = top_nodeset
  []
  [sigma1_pp]
    type = ParsedPostprocessor
    pp_names = stress_zz_top_pp
    expression = '-stress_zz_top_pp'
  []
  [differential_stress_mpa_pp]
    type = ParsedPostprocessor
    pp_names = sigma1_pp
    expression = '(sigma1_pp - 30e6) * 1e-6'
  []

  [differential_stress_skeleton_bulk_pp]
    type = ParsedPostprocessor
    pp_names = 'sigma1_pp sigma3_bulk_mpa_pp'
    expression = 'sigma1_pp * 1e-6 - sigma3_bulk_mpa_pp'
  []

  [differential_stress_biot_corrected_pp]
    type = ParsedPostprocessor
    pp_names = 'sigma1_pp fracture_pressure_mean_pp'
    expression = '(sigma1_pp + ${biot_coefficient} * fracture_pressure_mean_pp - 30e6) * 1e-6'
  []

  [differential_stress_biot_corrected_injection_pp]
    type = ParsedPostprocessor
    pp_names = 'sigma1_pp injection_pressure_pp'
    expression = '(sigma1_pp + ${biot_coefficient} * injection_pressure_pp - 30e6) * 1e-6'
  []

  [stress_zz_fault_pp]
    type = SideAverageValue
    variable = stress_zz
    boundary = fracture_interface
  []
  [stress_xx_fault_pp]
    type = SideAverageValue
    variable = stress_xx
    boundary = fracture_interface
  []
  [sigma1_fault_mpa_pp]
    type = ParsedPostprocessor
    pp_names = stress_zz_fault_pp
    expression = '-stress_zz_fault_pp * 1e-6'
  []
  [sigma3_fault_mpa_pp]
    type = ParsedPostprocessor
    pp_names = stress_xx_fault_pp
    expression = '-stress_xx_fault_pp * 1e-6'
  []

  [stress_xx_bulk_pp]
    type = ElementAverageValue
    variable = stress_xx
    block = 'top_block bottom_block'
  []
  [sigma3_bulk_mpa_pp]
    type = ParsedPostprocessor
    pp_names = stress_xx_bulk_pp
    expression = '-stress_xx_bulk_pp * 1e-6'
  []

  [czm_sigma_n_pp]
    type = ADSideAverageMaterialProperty
    property = czm_sigma_n
    boundary = fracture_interface
  []
  [interface_pressure_pp]
    type = ADSideAverageMaterialProperty
    property = interface_pore_pressure
    boundary = fracture_interface
  []

  [fracture_pressure_mean_pp]
    type = ADSideAverageMaterialProperty
    property = interface_pore_pressure
    boundary = fracture_interface
  []
  [bb_effective_normal_stress_pp]
    type = ParsedPostprocessor
    pp_names = 'czm_sigma_n_pp'
    expression = '-czm_sigma_n_pp'
  []

  [cumulative_plastic_slip_pp]
    type = SideAverageMaterialProperty
    property = cumulative_plastic_slip
    boundary = fracture_interface
  []
  [plastic_slip_increment_pp]
    type = SideAverageMaterialProperty
    property = plastic_slip_increment
    boundary = fracture_interface
  []
  [limit_tau_pp]
    type = SideAverageMaterialProperty
    property = limit_tau
    boundary = fracture_interface
  []

  [bb_limit_tau_pp]
    type = SideAverageMaterialProperty
    property = limit_tau
    boundary = fracture_interface
  []
  [friction_coefficient_effective_pp]
    type = SideAverageMaterialProperty
    property = friction_coefficient_effective
    boundary = fracture_interface
  []
  [cohesion_effective_pp]
    type = SideAverageMaterialProperty
    property = cohesion_effective
    boundary = fracture_interface
  []
  [roughness_state_pp]
    type = ADSideAverageMaterialProperty
    property = roughness_state
    boundary = fracture_interface
  []
  [bb_dilation_angle_pp]
    type = SideAverageMaterialProperty
    property = bb_dilation_angle_degrees
    boundary = fracture_interface
  []
  [dilation_jump_increment_pp]
    type = ADSideAverageMaterialProperty
    property = dilation_jump_increment
    boundary = fracture_interface
  []

  [czm_tau_1_pp]
    type = ADSideAverageMaterialProperty
    property = czm_tau_1
    boundary = fracture_interface
  []
  [czm_tau_2_pp]
    type = ADSideAverageMaterialProperty
    property = czm_tau_2
    boundary = fracture_interface
  []
  [shear_traction_magnitude_pa]
    type = ParsedPostprocessor
    pp_names = 'czm_tau_1_pp czm_tau_2_pp'
    expression = 'sqrt(czm_tau_1_pp^2 + czm_tau_2_pp^2)'
  []

  [czm_ds_1_pp]
    type = ADSideAverageMaterialProperty
    property = czm_ds_1
    boundary = fracture_interface
  []
  [czm_ds_2_pp]
    type = ADSideAverageMaterialProperty
    property = czm_ds_2
    boundary = fracture_interface
  []
  [czm_shear_slip_mm_pp]
    type = ParsedPostprocessor
    pp_names = 'czm_ds_1_pp czm_ds_2_pp'
    expression = 'sqrt(czm_ds_1_pp^2 + czm_ds_2_pp^2) * 1e3'
  []

  [reported_czm_shear_slip_mm_pp]
    type = ParsedPostprocessor
    pp_names = czm_shear_slip_mm_pp
    expression = 'czm_shear_slip_mm_pp * 1'
  []

  [hydraulic_aperture_pp]
    type = ADSideAverageMaterialProperty
    property = hydraulic_aperture
    boundary = fracture_interface
  []
  [hydraulic_aperture_um_pp]
    type = ParsedPostprocessor
    pp_names = hydraulic_aperture_pp
    expression = 'hydraulic_aperture_pp * 1e6'
  []
  [fracture_permeability_pp]
    type = ADSideAverageMaterialProperty
    property = fracture_permeability
    boundary = fracture_interface
  []
  [fracture_permeability_1e13_m2_pp]
    type = ParsedPostprocessor
    pp_names = fracture_permeability_pp
    expression = 'fracture_permeability_pp * 1e13'
  []
  [cumulative_dilation_pp]
    type = ADSideAverageMaterialProperty
    property = cumulative_dilation
    boundary = fracture_interface
  []
  [normal_stress_aperture_pp]
    type = ADSideAverageMaterialProperty
    property = normal_stress_aperture
    boundary = fracture_interface
  []
  [normal_stress_aperture_um_pp]
    type = ParsedPostprocessor
    pp_names = normal_stress_aperture_pp
    expression = 'normal_stress_aperture_pp * 1e6'
  []
  [slip_damage_aperture_pp]
    type = ADSideAverageMaterialProperty
    property = slip_damage_aperture
    boundary = fracture_interface
  []
  [slip_damage_aperture_um_pp]
    type = ParsedPostprocessor
    pp_names = slip_damage_aperture_pp
    expression = 'slip_damage_aperture_pp * 1e6'
  []
  [effective_normal_compression_pp]
    type = ADSideAverageMaterialProperty
    property = effective_normal_compression
    boundary = fracture_interface
  []
  [effective_normal_compression_mpa_pp]
    type = ParsedPostprocessor
    pp_names = effective_normal_compression_pp
    expression = 'effective_normal_compression_pp * 1e-6'
  []

  [czm_dn_pp]
    type = ADSideAverageMaterialProperty
    property = czm_dn
    boundary = fracture_interface
  []

  [czm_dn_total_pp]
    type = SideAverageMaterialProperty
    property = normal_opening_total
    boundary = fracture_interface
  []

  [czm_normal_dilation_paper_mm_pp]
    type = ParsedPostprocessor
    pp_names = czm_dn_total_pp
    expression = '-czm_dn_total_pp * 1e3'
  []

  [frac_normal_jump_avg]
    type = ADSideAverageMaterialProperty
    property = czm_dn_global
    boundary = fracture_interface
  []
  [frac_normal_dilation_paper_mm]
    type = ParsedPostprocessor
    pp_names = frac_normal_jump_avg
    expression = '-1.0e3 * frac_normal_jump_avg'
  []

  [mechanical_aperture_pp]
    type = ADSideAverageMaterialProperty
    property = mechanical_aperture
    boundary = fracture_interface
  []
  [mechanical_aperture_raw_pp]
    type = ADSideAverageMaterialProperty
    property = mechanical_aperture_raw
    boundary = fracture_interface
  []
  [aperture_open_pp]
    type = ParsedPostprocessor
    pp_names = frac_normal_jump_avg
    expression = 'if(frac_normal_jump_avg > 0.0, frac_normal_jump_avg, 0.0)'
  []

  [effective_normal_paper_frame_mpa_pp]
    type = ParsedPostprocessor
    pp_names = 'differential_stress_reaction_mpa_pp injection_pressure_pp pp_outlet_pp'
    expression = '33.0 - 0.5*(injection_pressure_pp + pp_outlet_pp)*1e-6 + 0.235040367883398*differential_stress_reaction_mpa_pp'
  []
  [shear_stress_paper_frame_mpa_pp]
    type = ParsedPostprocessor
    pp_names = differential_stress_reaction_mpa_pp
    expression = '0.424024048078213*differential_stress_reaction_mpa_pp'
  []


  # ---------------------------------------------------------------------------
  # 93-series: loading-frame and bulk-kinematics diagnostics.  These existed only
  # on SW-S4 (87 postprocessors vs 70 on the other three), which made the four
  # specimens impossible to compare channel-for-channel.  Nothing here feeds the
  # Table-2 gate; they are diagnostics.  Task #82.
  # ---------------------------------------------------------------------------
  [axial_command_m_pp]
    type = FunctionValuePostprocessor
    function = axial_disp_ramp
  []
  [top_disp_z_mean_m_pp]
    type = SideAverageValue
    variable = disp_z
    boundary = top_nodeset
  []
  [machine_spring_gap_m_pp]
    type = ParsedPostprocessor
    pp_names = 'top_disp_z_mean_m_pp axial_command_m_pp'
    expression = 'top_disp_z_mean_m_pp - axial_command_m_pp'
  []
  [machine_spring_sigma1_mpa_pp]
    type = ParsedPostprocessor
    pp_names = machine_spring_gap_m_pp
    expression = 'abs(machine_spring_gap_m_pp) * ${axial_bc_penalty} * 1e-6'
  []
  [reaction_vs_machine_spring_mpa_pp]
    type = ParsedPostprocessor
    pp_names = 'sigma1_reaction_mpa_pp machine_spring_sigma1_mpa_pp'
    expression = 'sigma1_reaction_mpa_pp - machine_spring_sigma1_mpa_pp'
  []

  # Barton-Bandis envelope evolution.  All six are declared by
  # OrcaBartonBandisContactTractionFastADHardening on every BBFast deck.
  [bb_normal_closure_pp]
    type = ADSideAverageMaterialProperty
    property = bb_normal_closure
    boundary = fracture_interface
  []
  [bb_normal_closure_um_pp]
    type = ParsedPostprocessor
    pp_names = bb_normal_closure_pp
    expression = 'bb_normal_closure_pp * 1e6'
  []
  [bb_law_normal_stress_pp]           # sigma_n the BB law computed from its closure (Pa, +compression)
    type = SideAverageMaterialProperty
    property = bb_compressive_normal_stress
    boundary = fracture_interface
  []
  [bb_peak_friction_angle_pp]
    type = SideAverageMaterialProperty
    property = bb_peak_friction_angle_degrees
    boundary = fracture_interface
  []
  [bb_mu_peak_pp]
    type = SideAverageMaterialProperty
    property = bb_peak_friction_coefficient
    boundary = fracture_interface
  []
  [bb_jrc_mobilized_pp]
    type = SideAverageMaterialProperty
    property = bb_jrc_mobilized
    boundary = fracture_interface
  []
  [bb_normal_stiffness_tangent_pp]    # tangent Kn along the power-law closure (Pa/m)
    type = SideAverageMaterialProperty
    property = bb_normal_stiffness_tangent
    boundary = fracture_interface
  []

  # Bulk (LVDT-analogue) kinematics: two probes on the cylinder surface straddling
  # the fracture, resolved onto the fracture plane with THIS specimen's theta.
  # 93-series rule: z = L/2 +- 50 mm, i.e. a 100 mm gauge on all four specimens.
  [bulk_disp_x_upper_pp]
    type = PointValue
    variable = disp_x
    point = '${sample_radius} 0 0.10500'
  []
  [bulk_disp_z_upper_pp]
    type = PointValue
    variable = disp_z
    point = '${sample_radius} 0 0.10500'
  []
  [bulk_disp_x_lower_pp]
    type = PointValue
    variable = disp_x
    point = '${sample_radius} 0 0.01500'
  []
  [bulk_disp_z_lower_pp]
    type = PointValue
    variable = disp_z
    point = '${sample_radius} 0 0.01500'
  []
  [bulk_delta_x_pp]
    type = ParsedPostprocessor
    pp_names = 'bulk_disp_x_upper_pp bulk_disp_x_lower_pp'
    expression = 'bulk_disp_x_upper_pp - bulk_disp_x_lower_pp'
  []
  [bulk_delta_z_pp]
    type = ParsedPostprocessor
    pp_names = 'bulk_disp_z_upper_pp bulk_disp_z_lower_pp'
    expression = 'bulk_disp_z_upper_pp - bulk_disp_z_lower_pp'
  []
  [bulk_normal_dilation_paper_mm_pp]
    type = ParsedPostprocessor
    pp_names = 'bulk_delta_x_pp bulk_delta_z_pp'
    expression = '-(bulk_delta_x_pp*${bulk_cos_theta} - bulk_delta_z_pp*${bulk_sin_theta}) * 1e3'
  []
  [bulk_shear_slip_mm_pp]
    type = ParsedPostprocessor
    pp_names = 'bulk_delta_x_pp bulk_delta_z_pp'
    expression = 'abs(bulk_delta_x_pp*${bulk_sin_theta} + bulk_delta_z_pp*${bulk_cos_theta}) * 1e3'
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
    petsc_options_iname = '-pc_type -pc_factor_mat_solver_package'
    petsc_options_value = ' lu       mumps'
  []
[]

[Executioner]
  type = Transient
  solve_type = Newton
  line_search = l2
  start_time = 0
  end_time = 2000   # ROUND 8: stop after stage 5

  [TimeStepper]
    type = IterationAdaptiveDT
    # ROUND 3: per-segment dt limit. Ramps (100 s, the load actually moves)
    # keep 1.5 s; holds (300 s, where round 2 converged at
    # nonlinear iteration 0 and a_h/Q/slip moved <0.1/0.4/2 %) get 5.0 s.
    # 4800 forced steps -> 1140. dtmin and the cutback are untouched,
    # so a stick-slip event still resolves itself down to 1e-6 s.
    time_t  = '0.0 0.5 99.5 100.5 399.5 400.5 499.5 500.5 799.5 800.5 899.5 900.5 1199.5 1200.5 1299.5 1300.5 1599.5 1600.5 1699.5 1700.5 1999.5 2000.5 2099.5 2100.5 2399.5 2400.5 2499.5 2500.5 2799.5 2800.5 2899.5 2900.5 3199.5 3200.5 3299.5 3300.5 3599.5 3600.0'
    time_dt = '1.50 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50 1.50 5.00 5.00 1.50'
    # Land exactly on every injection breakpoint, so a hold-end sample is
    # never straddled by a step that started inside the ramp.
    timestep_limiting_function = injection_pressure
    force_step_every_function_point = true
    dt = 0.75
    optimal_iterations = 18
    growth_factor = 1.2
    cutback_factor = 0.5
  []

  dtmax = 5.0   # ROUND 3: was 0.75; time_t/time_dt now govern
  dtmin = 1e-6
  l_max_its = 50
  l_tol = 1e-4
  nl_max_its = 70
  nl_abs_tol = 1e-4

  nl_rel_tol = 1e-6
[]

[Outputs]
  [console]
    type = Console
    execute_postprocessors_on = none
  []
  [csv]
    type = CSV
    file_base = ${csv_file_base}
  []
  [exodus]
    type = Exodus
    file_base = ${exodus_file_base}
    execute_on = 'TIMESTEP_END FINAL'
    time_step_interval = 2
  []
  [chk]
    type = Checkpoint
    file_base = ${checkpoint_file_base}
    time_step_interval = 800
    num_files = 1
  []
[]
